import { BoardSquare, CategoryType } from '../types/game';

export const CATEGORY_CONFIG: Record<
  CategoryType,
  {
    label: string;
    description: string;
    bgClass: string;
    badgeClass: string;
    textColor: string;
    borderClass: string;
  }
> = {
  start: {
    label: 'Bắt đầu',
    description: 'Ô xuất phát của hành trình dân chủ',
    bgClass: 'bg-slate-900',
    badgeClass: 'bg-amber-400 text-slate-950 font-black',
    textColor: 'text-amber-300',
    borderClass: 'border-amber-400',
  },
  politics: {
    label: 'Chính trị',
    description: 'Bản chất chính trị: quyền lực thuộc về nhân dân, tham gia quản lý nhà nước',
    bgClass: 'bg-rose-50',
    badgeClass: 'bg-rose-600 text-white',
    textColor: 'text-rose-950',
    borderClass: 'border-rose-300',
  },
  economy: {
    label: 'Kinh tế',
    description: 'Bản chất kinh tế: sở hữu TLSX chủ yếu, phân phối theo lao động',
    bgClass: 'bg-amber-50',
    badgeClass: 'bg-amber-600 text-white',
    textColor: 'text-amber-950',
    borderClass: 'border-amber-300',
  },
  culture_society: {
    label: 'Văn hóa – Xã hội',
    description: 'Bản chất tư tưởng - VH - XH: phát huy văn hóa dân tộc, nâng cao dân trí',
    bgClass: 'bg-sky-50',
    badgeClass: 'bg-sky-600 text-white',
    textColor: 'text-sky-950',
    borderClass: 'border-sky-300',
  },
  law: {
    label: 'Pháp luật',
    description: 'Thể chế hóa quyền dân chủ, kỷ luật, kỷ cương và pháp quyền XHCN',
    bgClass: 'bg-emerald-50',
    badgeClass: 'bg-emerald-600 text-white',
    textColor: 'text-emerald-950',
    borderClass: 'border-emerald-300',
  },
  knowledge: {
    label: 'Kiến thức cốt lõi',
    description: 'Khái niệm, nguồn gốc và quá trình phát triển của nền dân chủ',
    bgClass: 'bg-orange-50',
    badgeClass: 'bg-orange-500 text-white',
    textColor: 'text-orange-950',
    borderClass: 'border-orange-300',
  },
  scenario: {
    label: 'Tình huống thực tế',
    description: 'Vận dụng kiến thức giải quyết tình huống thực tiễn sinh động',
    bgClass: 'bg-purple-50',
    badgeClass: 'bg-purple-600 text-white',
    textColor: 'text-purple-950',
    borderClass: 'border-purple-300',
  },
};

export const BOARD_SQUARES: BoardSquare[] = [
  {
    id: 1,
    name: 'BẮT ĐẦU – NHÂN DÂN LÀM CHỦ',
    category: 'start',
    subtitle: 'Xuất phát điểm của hành trình dân chủ',
    questions: [
      {
        id: 'sq1_q1',
        text: 'Khẩu hiệu cốt lõi của nền dân chủ Xã hội Chủ nghĩa là gì?',
        answer: 'Dân là chủ và Dân làm chủ.',
        hint: 'Dân là c__ và Dân l__  c__.',
        acceptedAnswers: ['Dân là chủ và Dân làm chủ.'],
        explanation: 'Khẩu hiệu cốt lõi của nền dân chủ XHCN.',
      },
      {
        id: 'sq1_q2',
        text: 'Bản chất cao nhất của nền dân chủ XHCN là mọi quyền lực thuộc về ai?',
        answer: 'Thuộc về toàn thể Nhân dân.',
        hint: 'Thuộc về toàn thể N___  d__.',
        acceptedAnswers: ['Thuộc về toàn thể Nhân dân.'],
        explanation: 'Bản chất quyền lực thuộc về nhân dân.',
      },
      {
        id: 'sq1_q3',
        text: 'Nền dân chủ XHCN đặt dưới sự lãnh đạo của tổ chức chính trị nào?',
        answer: 'Đảng Cộng sản Việt Nam.',
        hint: 'Đ___  C___  s__ Việt Nam.',
        acceptedAnswers: ['Đảng Cộng sản Việt Nam.'],
        explanation: 'Sự lãnh đạo của Đảng Cộng sản.',
      },
      {
        id: 'sq1_q4',
        text: 'Nhà nước bảo đảm quyền làm chủ của nhân dân là nhà nước gì?',
        answer: 'Nhà nước pháp quyền xã hội chủ nghĩa của nhân dân, do nhân dân, vì nhân dân.',
        hint: 'Nhà nước p___  q____ xã hội chủ nghĩa.',
        acceptedAnswers: ['Nhà nước pháp quyền xã hội chủ nghĩa của nhân dân, do nhân dân, vì nhân dân.'],
        explanation: 'Nhà nước pháp quyền XHCN.',
      },
    ],
  },
  {
    id: 2,
    name: 'KIẾN THỨC: KHÁI NIỆM DÂN CHỦ',
    category: 'knowledge',
    subtitle: 'Nguồn gốc và bản chất khái niệm dân chủ',
    questions: [
      {
        id: 'sq2_q1',
        text: 'Theo tư tưởng Hồ Chí Minh được giáo trình trình bày, dân chủ được diễn đạt ngắn gọn bằng hai vế nào?',
        hint: 'Dân là c__ và dân l__  c__.',
        answer: 'Dân là chủ và dân làm chủ.',
        acceptedAnswers: ['Dân là chủ và dân làm chủ.'],
        explanation: 'Dân là chủ và dân làm chủ.',
      },
      {
        id: 'sq2_q2',
        text: 'Dân chủ có thể được tiếp cận dưới ba tư cách cơ bản nào?',
        hint: 'Một giá trị x_  h__;\nMột phạm trù c____  t__;\nMột phạm trù l___  s_.',
        answer: 'Một giá trị xã hội; một phạm trù chính trị; một phạm trù lịch sử.',
        acceptedAnswers: ['Một giá trị xã hội; một phạm trù chính trị; một phạm trù lịch sử.'],
        explanation: 'Một giá trị xã hội; một phạm trù chính trị; một phạm trù lịch sử.',
      },
      {
        id: 'sq2_q3',
        text: 'Dân chủ với tư cách một giá trị xã hội phản ánh điều gì?',
        hint: 'Những quyền c_  b__ của con người.',
        answer: 'Những quyền cơ bản của con người.',
        acceptedAnswers: ['Những quyền cơ bản của con người.'],
        explanation: 'Những quyền cơ bản của con người.',
      },
      {
        id: 'sq2_q4',
        text: 'Theo giáo trình, dân chủ phải bao quát những lĩnh vực chủ yếu nào của đời sống?',
        hint: 'K___  t_, c____  t__, x_  h__ và văn hóa – t___  t___ – tư tưởng.',
        answer: 'Kinh tế, chính trị, xã hội và văn hóa – tinh thần – tư tưởng.',
        acceptedAnswers: ['Kinh tế, chính trị, xã hội và văn hóa – tinh thần – tư tưởng.'],
        explanation: 'Kinh tế, chính trị, xã hội và văn hóa – tinh thần – tư tưởng.',
      },
    ],
  },
  {
    id: 3,
    name: 'PHÁT TRIỂN KINH TẾ BỀN VỮNG',
    category: 'economy',
    subtitle: 'Cơ sở kinh tế của nền dân chủ',
    questions: [
      {
        id: 'sq3_q1',
        text: 'Trong các lĩnh vực dân chủ, giáo trình coi dân chủ trên lĩnh vực nào là cơ sở?',
        hint: 'Dân chủ trên lĩnh vực k___  t_.',
        answer: 'Dân chủ trên lĩnh vực kinh tế.',
        acceptedAnswers: ['Dân chủ trên lĩnh vực kinh tế.'],
        explanation: 'Dân chủ trên lĩnh vực kinh tế.',
      },
      {
        id: 'sq3_q2',
        text: 'Bản chất kinh tế của nền dân chủ XHCN hướng tới thỏa mãn ngày càng cao nhu cầu của ai?',
        hint: 'Toàn thể n___  d__  l__  đ___.',
        answer: 'Toàn thể nhân dân lao động.',
        acceptedAnswers: ['Toàn thể nhân dân lao động.'],
        explanation: 'Toàn thể nhân dân lao động.',
      },
      {
        id: 'sq3_q3',
        text: 'Quyền làm chủ về kinh tế của nhân dân được thể hiện trước hết ở quyền làm chủ đối với những gì?',
        hint: 'Những tư liệu s__  x___ c__  y__ của xã hội.',
        answer: 'Những tư liệu sản xuất chủ yếu của xã hội.',
        acceptedAnswers: ['Những tư liệu sản xuất chủ yếu của xã hội.'],
        explanation: 'Những tư liệu sản xuất chủ yếu của xã hội.',
      },
      {
        id: 'sq3_q4',
        text: 'Vì sao lợi ích kinh tế của người lao động có ý nghĩa đối với phát triển kinh tế – xã hội?',
        hint: 'Đó là một đ___  l__  c_  b__ thúc đẩy kinh tế – xã hội phát triển.',
        answer: 'Vì giáo trình coi đó là một động lực cơ bản thúc đẩy kinh tế – xã hội phát triển.',
        acceptedAnswers: ['Vì giáo trình coi đó là một động lực cơ bản thúc đẩy kinh tế – xã hội phát triển.'],
        explanation: 'Vì giáo trình coi đó là một động lực cơ bản thúc đẩy kinh tế – xã hội phát triển.',
      },
    ],
  },
  {
    id: 4,
    name: 'PHÁP LUẬT',
    category: 'law',
    subtitle: 'Kỷ luật, kỷ cương và thể chế hóa',
    questions: [
      {
        id: 'sq4_q1',
        text: 'Dân chủ và pháp luật trong nền dân chủ XHCN có quan hệ như thế nào?',
        hint: 'Nằm trong sự t____  n___  b___  c____.',
        answer: 'Nằm trong sự thống nhất biện chứng.',
        acceptedAnswers: ['Nằm trong sự thống nhất biện chứng.'],
        explanation: 'Nằm trong sự thống nhất biện chứng.',
      },
      {
        id: 'sq4_q2',
        text: 'Dân chủ phải đi đôi với những yêu cầu nào để bảo đảm trật tự xã hội?',
        hint: 'K_  l___ và k_  c____.',
        answer: 'Kỷ luật và kỷ cương.',
        acceptedAnswers: ['Kỷ luật và kỷ cương.'],
        explanation: 'Kỷ luật và kỷ cương.',
      },
      {
        id: 'sq4_q3',
        text: 'Dân chủ phải được thể chế hóa và bảo đảm bằng gì?',
        hint: 'P___  l___.',
        answer: 'Pháp luật.',
        acceptedAnswers: ['Pháp luật.'],
        explanation: 'Pháp luật.',
      },
      {
        id: 'sq4_q4',
        text: 'Đúng hay sai: Có quyền dân chủ nghĩa là có thể hành động ngoài khuôn khổ pháp luật.',
        hint: 'Sai. Quyền dân chủ được thể chế hóa và bảo đảm bằng p___  l___, đồng thời gắn với k_  l___, k_  c____.',
        answer: 'Sai. Quyền dân chủ được thể chế hóa và bảo đảm bằng pháp luật, đồng thời gắn với kỷ luật, kỷ cương.',
        acceptedAnswers: ['Sai. Quyền dân chủ được thể chế hóa và bảo đảm bằng pháp luật, đồng thời gắn với kỷ luật, kỷ cương.'],
        explanation: 'Sai. Quyền dân chủ được thể chế hóa và bảo đảm bằng pháp luật, đồng thời gắn với kỷ luật, kỷ cương.',
      },
    ],
  },
  {
    id: 5,
    name: 'TÌNH HUỐNG 1',
    category: 'scenario',
    subtitle: 'Tình huống pháp luật và quyền làm chủ',
    questions: [
      {
        id: 'sq5_q1',
        text: 'Một người nói: “Tôi là chủ nên tôi muốn làm gì cũng được, không cần tuân thủ quy định chung”. Hãy nhận xét.',
        hint: 'Không đúng; dân chủ phải gắn với p___  l___, k_  l___ và k_  c____.',
        answer: 'Không đúng; dân chủ phải gắn với pháp luật, kỷ luật và kỷ cương.',
        acceptedAnswers: ['Không đúng; dân chủ phải gắn với pháp luật, kỷ luật và kỷ cương.'],
        explanation: 'Không đúng; dân chủ phải gắn với pháp luật, kỷ luật và kỷ cương.',
      },
      {
        id: 'sq5_q2',
        text: 'Một địa phương chuẩn bị quyết định vấn đề ảnh hưởng trực tiếp đến dân nhưng không tạo điều kiện để người dân tham gia ý kiến. Nội dung nào của dân chủ chưa được thể hiện đầy đủ?',
        hint: 'Quyền l__  c__ và quyền tham gia q___  l_ nhà nước, xã hội của nhân dân.',
        answer: 'Quyền làm chủ và quyền tham gia quản lý nhà nước, xã hội của nhân dân.',
        acceptedAnswers: ['Quyền làm chủ và quyền tham gia quản lý nhà nước, xã hội của nhân dân.'],
        explanation: 'Quyền làm chủ và quyền tham gia quản lý nhà nước, xã hội của nhân dân.',
      },
      {
        id: 'sq5_q3',
        text: 'Một chính sách chỉ chú ý lợi ích của một nhóm nhỏ, bỏ qua lợi ích tập thể và xã hội. Theo bản chất xã hội của dân chủ XHCN cần điều chỉnh theo hướng nào?',
        hint: 'Kết hợp hài hòa lợi ích c_  _h_n, t__  t__ và t___  x_  h__.',
        answer: 'Kết hợp hài hòa lợi ích cá nhân, tập thể và toàn xã hội.',
        acceptedAnswers: ['Kết hợp hài hòa lợi ích cá nhân, tập thể và toàn xã hội.'],
        explanation: 'Kết hợp hài hòa lợi ích cá nhân, tập thể và toàn xã hội.',
      },
      {
        id: 'sq5_q4',
        text: 'Người lao động được tham gia quản lý sản xuất nhưng kết quả phân phối hoàn toàn không gắn với lao động. Nội dung nào cần xem xét?',
        hint: 'Bản chất k___  t_;\nphân phối lợi ích theo k__  q__ lao động là chủ yếu.',
        answer: 'Bản chất kinh tế; phân phối lợi ích theo kết quả lao động là chủ yếu.',
        acceptedAnswers: ['Bản chất kinh tế; phân phối lợi ích theo kết quả lao động là chủ yếu.'],
        explanation: 'Bản chất kinh tế; phân phối lợi ích theo kết quả lao động là chủ yếu.',
      },
    ],
  },
  {
    id: 6,
    name: 'THAM GIA QUẢN LÝ XÃ HỘI',
    category: 'politics',
    subtitle: 'Bản chất chính trị của dân chủ',
    questions: [
      {
        id: 'sq6_q1',
        text: 'Việc nhân dân tham gia quản lý xã hội thể hiện trực tiếp phương diện bản chất nào của nền dân chủ XHCN?',
        hint: 'Bản chất c____  t__.',
        answer: 'Bản chất chính trị.',
        acceptedAnswers: ['Bản chất chính trị.'],
        explanation: 'Bản chất chính trị.',
      },
      {
        id: 'sq6_q2',
        text: 'Theo giáo trình, sự tham gia rộng rãi của nhân dân vào công việc quản lý nhà nước được gọi là gì?',
        hint: 'Dân chủ về c____  t__.',
        answer: 'Dân chủ về chính trị.',
        acceptedAnswers: ['Dân chủ về chính trị.'],
        explanation: 'Dân chủ về chính trị.',
      },
      {
        id: 'sq6_q3',
        text: 'Ngoài quản lý nhà nước, nhân dân còn thực hiện quyền làm chủ trong phạm vi nào?',
        hint: 'Trong t_an  x_  _oi và các l_nh  _uc của đ_i  số__  x_  _oi.',
        answer: 'Trong toàn xã hội và các lĩnh vực của đời sống xã hội.',
        acceptedAnswers: ['Trong toàn xã hội và các lĩnh vực của đời sống xã hội.'],
        explanation: 'Trong toàn xã hội và các lĩnh vực của đời sống xã hội.',
      },
      {
        id: 'sq6_q4',
        text: 'Mục đích của việc thu hút ngày càng đông đảo nhân dân tham gia quản lý xã hội là gì?',
        hint: 'Để nhân dân thực sự thực hiện quyền l__  c__ và tham gia tự giác vào q___  l_ nhà nước, q___  l_ xã hội.',
        answer: 'Để nhân dân thực sự thực hiện quyền làm chủ và tham gia tự giác vào quản lý nhà nước, quản lý xã hội.',
        acceptedAnswers: ['Để nhân dân thực sự thực hiện quyền làm chủ và tham gia tự giác vào quản lý nhà nước, quản lý xã hội.'],
        explanation: 'Để nhân dân thực sự thực hiện quyền làm chủ và tham gia tự giác vào quản lý nhà nước, quản lý xã hội.',
      },
    ],
  },
  {
    id: 7,
    name: 'BẦU CỬ',
    category: 'politics',
    subtitle: 'Thực hiện quyền dân chủ trực tiếp và đại diện',
    questions: [
      {
        id: 'sq7_q1',
        text: 'Việc nhân dân lựa chọn người đại diện cho mình thể hiện rõ nhất quyền làm chủ trên lĩnh vực nào?',
        hint: 'C____  t__.',
        answer: 'Chính trị.',
        acceptedAnswers: ['Chính trị.'],
        explanation: 'Chính trị.',
      },
      {
        id: 'sq7_q2',
        text: 'Bầu cử thể hiện rõ hơn vế “dân là chủ” hay “dân làm chủ”?',
        hint: 'Dân l__  c__, vì nhân dân trực tiếp thực hiện quyền c____  t__ của mình.',
        answer: 'Dân làm chủ, vì nhân dân trực tiếp thực hiện quyền chính trị của mình.',
        acceptedAnswers: ['Dân làm chủ, vì nhân dân trực tiếp thực hiện quyền chính trị của mình.'],
        explanation: 'Dân làm chủ, vì nhân dân trực tiếp thực hiện quyền chính trị của mình.',
      },
      {
        id: 'sq7_q3',
        text: 'Theo nội dung giáo trình, nhân dân có quyền giới thiệu những người nào tham gia vào bộ máy chính quyền?',
        hint: 'Những đ__  b___ của mình.',
        answer: 'Những đại biểu của mình.',
        acceptedAnswers: ['Những đại biểu của mình.'],
        explanation: 'Những đại biểu của mình.',
      },
      {
        id: 'sq7_q4',
        text: 'Thông qua đại diện do nhân dân lựa chọn và các hình thức dân chủ trực tiếp, nguyên tắc cốt lõi nào được bảo đảm?',
        hint: 'Quyền lực thuộc về n___  d__.',
        answer: 'Quyền lực thuộc về nhân dân.',
        acceptedAnswers: ['Quyền lực thuộc về nhân dân.'],
        explanation: 'Quyền lực thuộc về nhân dân.',
      },
    ],
  },
  {
    id: 8,
    name: 'KIẾN THỨC: SỰ RA ĐỜI VÀ PHÁT TRIỂN CỦA DÂN CHỦ',
    category: 'knowledge',
    subtitle: 'Các giai đoạn phát triển lịch sử của dân chủ',
    questions: [
      {
        id: 'sq8_q1',
        text: 'Hình thức dân chủ sơ khai trong xã hội cộng sản nguyên thủy còn được gọi là gì?',
        hint: 'Dân chủ n____  t___ / dân chủ q___  s_.',
        answer: 'Dân chủ nguyên thủy / dân chủ quân sự.',
        acceptedAnswers: ['Dân chủ nguyên thủy / dân chủ quân sự.'],
        explanation: 'Dân chủ nguyên thủy / dân chủ quân sự.',
      },
      {
        id: 'sq8_q2',
        text: 'Trong xã hội chiếm hữu nô lệ xuất hiện nền dân chủ của giai cấp nào?',
        hint: 'Dân chủ c__  n_.',
        answer: 'Dân chủ chủ nô.',
        acceptedAnswers: ['Dân chủ chủ nô.'],
        explanation: 'Dân chủ chủ nô.',
      },
      {
        id: 'sq8_q3',
        text: 'Nền dân chủ XHCN chính thức được xác lập sau sự kiện nào?',
        hint: 'Sau thắng lợi của Cách mạng T____  M___ Nga năm 19__ và sự ra đời của nhà nước XHCN đầu tiên.',
        answer: 'Sau thắng lợi của Cách mạng Tháng Mười Nga năm 1917 và sự ra đời của nhà nước XHCN đầu tiên.',
        acceptedAnswers: ['Sau thắng lợi của Cách mạng Tháng Mười Nga năm 1917 và sự ra đời của nhà nước XHCN đầu tiên.'],
        explanation: 'Sau thắng lợi của Cách mạng Tháng Mười Nga năm 1917 và sự ra đời của nhà nước XHCN đầu tiên.',
      },
      {
        id: 'sq8_q4',
        text: 'Nền dân chủ XHCN phát triển theo xu hướng nào?',
        hint: 'Từ t___ đến c__, từ chưa hoàn thiện đến hoàn thiện và có sự k_  t___ chọn lọc các giá trị dân chủ trước đó.',
        answer: 'Từ thấp đến cao, từ chưa hoàn thiện đến hoàn thiện và có sự kế thừa chọn lọc các giá trị dân chủ trước đó.',
        acceptedAnswers: ['Từ thấp đến cao, từ chưa hoàn thiện đến hoàn thiện và có sự kế thừa chọn lọc các giá trị dân chủ trước đó.'],
        explanation: 'Từ thấp đến cao, từ chưa hoàn thiện đến hoàn thiện và có sự kế thừa chọn lọc các giá trị dân chủ trước đó.',
      },
    ],
  },
  {
    id: 9,
    name: 'SẢN XUẤT VÀ LAO ĐỘNG',
    category: 'economy',
    subtitle: 'Lao động và làm chủ tư liệu sản xuất',
    questions: [
      {
        id: 'sq9_q1',
        text: 'Trong sản xuất, người lao động thực hiện quyền làm chủ thông qua những hoạt động nào?',
        hint: 'Tham gia s__  x___, k___  d____ và q___  l_.',
        answer: 'Tham gia sản xuất, kinh doanh và quản lý.',
        acceptedAnswers: ['Tham gia sản xuất, kinh doanh và quản lý.'],
        explanation: 'Tham gia sản xuất, kinh doanh và quản lý.',
      },
      {
        id: 'sq9_q2',
        text: 'Theo bản chất kinh tế của dân chủ XHCN, nhân dân làm chủ những tư liệu nào?',
        hint: 'Những tư l___ sản x___ chủ yếu.',
        answer: 'Những tư liệu sản xuất chủ yếu.',
        acceptedAnswers: ['Những tư liệu sản xuất chủ yếu.'],
        explanation: 'Những tư liệu sản xuất chủ yếu.',
      },
      {
        id: 'sq9_q3',
        text: 'Lợi ích kinh tế của lực lượng nào được coi là một động lực cơ bản?',
        hint: 'Người l__  đ___.',
        answer: 'Người lao động.',
        acceptedAnswers: ['Người lao động.'],
        explanation: 'Người lao động.',
      },
      {
        id: 'sq9_q4',
        text: 'Bản chất kinh tế của dân chủ XHCN dựa trên sự phát triển của lực lượng sản xuất ở trình độ nào?',
        hint: 'Trình độ c__/hiện đại, nhằm đáp ứng ngày càng cao nhu cầu v__  c___ và t___  t___ của nhân dân.',
        answer: 'Trình độ cao/hiện đại, nhằm đáp ứng ngày càng cao nhu cầu vật chất và tinh thần của nhân dân.',
        acceptedAnswers: ['Trình độ cao/hiện đại, nhằm đáp ứng ngày càng cao nhu cầu vật chất và tinh thần của nhân dân.'],
        explanation: 'Trình độ cao/hiện đại, nhằm đáp ứng ngày càng cao nhu cầu vật chất và tinh thần của nhân dân.',
      },
    ],
  },
  {
    id: 10,
    name: 'TÌNH HUỐNG 2',
    category: 'scenario',
    subtitle: 'Tình huống kinh tế và văn hóa xã hội',
    questions: [
      {
        id: 'sq10_q1',
        text: 'Một doanh nghiệp cho người lao động tham gia góp ý cách tổ chức sản xuất và quản lý. Tình huống này thể hiện phương diện nào?',
        hint: 'Bản chất k___  t_ của nền dân chủ XHCN.',
        answer: 'Bản chất kinh tế của nền dân chủ XHCN.',
        acceptedAnswers: ['Bản chất kinh tế của nền dân chủ XHCN.'],
        explanation: 'Bản chất kinh tế của nền dân chủ XHCN.',
      },
      {
        id: 'sq10_q2',
        text: 'Một chương trình phát triển chỉ tăng sản lượng nhưng không quan tâm nhu cầu vật chất, tinh thần của người lao động. Theo bài học còn thiếu định hướng nào?',
        hint: 'Phát triển kinh tế phải hướng tới thỏa mãn ngày càng cao nhu cầu v__  c___ và t___  t___ của nhân dân lao động.',
        answer: 'Phát triển kinh tế phải hướng tới thỏa mãn ngày càng cao nhu cầu vật chất và tinh thần của nhân dân lao động.',
        acceptedAnswers: ['Phát triển kinh tế phải hướng tới thỏa mãn ngày càng cao nhu cầu vật chất và tinh thần của nhân dân lao động.'],
        explanation: 'Phát triển kinh tế phải hướng tới thỏa mãn ngày càng cao nhu cầu vật chất và tinh thần của nhân dân lao động.',
      },
      {
        id: 'sq10_q3',
        text: 'Người dân được mời góp ý dự thảo chính sách của địa phương. Đây là biểu hiện của quyền làm chủ nào?',
        hint: 'Quyền l__  c__ c____  t__, tham gia q___  l_ nhà nước và xây dựng c____  s___.',
        answer: 'Quyền làm chủ chính trị, tham gia quản lý nhà nước và xây dựng chính sách.',
        acceptedAnswers: ['Quyền làm chủ chính trị, tham gia quản lý nhà nước và xây dựng chính sách.'],
        explanation: 'Quyền làm chủ chính trị, tham gia quản lý nhà nước và xây dựng chính sách.',
      },
      {
        id: 'sq10_q4',
        text: 'Một hoạt động văn hóa loại bỏ hoàn toàn truyền thống để chạy theo cái mới. Có phù hợp với bản chất văn hóa của dân chủ XHCN không?',
        hint: 'Không; cần k_  t___, phát huy tinh hoa văn hóa dân tộc đồng thời tiếp thu giá trị t___  b_ của nhân loại.',
        answer: 'Không; cần kế thừa, phát huy tinh hoa văn hóa dân tộc đồng thời tiếp thu giá trị tiến bộ của nhân loại.',
        acceptedAnswers: ['Không; cần kế thừa, phát huy tinh hoa văn hóa dân tộc đồng thời tiếp thu giá trị tiến bộ của nhân loại.'],
        explanation: 'Không; cần kế thừa, phát huy tinh hoa văn hóa dân tộc đồng thời tiếp thu giá trị tiến bộ của nhân loại.',
      },
    ],
  },
  {
    id: 11,
    name: 'GIÁO DỤC',
    category: 'culture_society',
    subtitle: 'Nâng cao dân trí và phát triển cá nhân',
    questions: [
      {
        id: 'sq11_q1',
        text: 'Theo bản chất tư tưởng – văn hóa – xã hội, nâng cao trình độ văn hóa của nhân dân nhằm tạo điều kiện cho điều gì?',
        hint: 'Cho nhân dân l__  c__ đời sống t___  t___ và có điều kiện phát triển c_  _h_n.',
        answer: 'Cho nhân dân làm chủ đời sống tinh thần và có điều kiện phát triển cá nhân.',
        acceptedAnswers: ['Cho nhân dân làm chủ đời sống tinh thần và có điều kiện phát triển cá nhân.'],
        explanation: 'Cho nhân dân làm chủ đời sống tinh thần và có điều kiện phát triển cá nhân.',
      },
      {
        id: 'sq11_q2',
        text: 'Việc tạo cơ hội học tập và nâng cao trình độ của người dân gắn với phương diện bản chất nào?',
        hint: 'T_  t____ – văn hóa – x_  h__.',
        answer: 'Tư tưởng – văn hóa – xã hội.',
        acceptedAnswers: ['Tư tưởng – văn hóa – xã hội.'],
        explanation: 'Tư tưởng – văn hóa – xã hội.',
      },
      {
        id: 'sq11_q3',
        text: 'Nhân dân không chỉ là người hưởng thụ mà còn có vai trò gì đối với các giá trị văn hóa, tinh thần?',
        hint: 'L__  c__ và tham gia s___  t__ các giá trị văn hóa, tinh thần.',
        answer: 'Làm chủ và tham gia sáng tạo các giá trị văn hóa, tinh thần.',
        acceptedAnswers: ['Làm chủ và tham gia sáng tạo các giá trị văn hóa, tinh thần.'],
        explanation: 'Làm chủ và tham gia sáng tạo các giá trị văn hóa, tinh thần.',
      },
      {
        id: 'sq11_q4',
        text: 'Trong các điều kiện để quyền lực thực sự thuộc về nhân dân, giáo trình nhấn mạnh cần nâng cao yếu tố nào của người dân?',
        hint: 'Trình độ d__  t__.',
        answer: 'Trình độ dân trí.',
        acceptedAnswers: ['Trình độ dân trí.'],
        explanation: 'Trình độ dân trí.',
      },
    ],
  },
  {
    id: 12,
    name: 'PHÁP LUẬT VÀ BẢO ĐẢM QUYỀN DÂN CHỦ',
    category: 'law',
    subtitle: 'Cơ chế pháp luật bảo đảm quyền con người',
    questions: [
      {
        id: 'sq12_q1',
        text: 'Pháp luật có vai trò gì đối với việc thực hiện dân chủ?',
        hint: 'T__  c__ hóa và b__  đ__ việc thực hiện các quyền dân chủ.',
        answer: 'Thể chế hóa và bảo đảm việc thực hiện các quyền dân chủ.',
        acceptedAnswers: ['Thể chế hóa và bảo đảm việc thực hiện các quyền dân chủ.'],
        explanation: 'Thể chế hóa và bảo đảm việc thực hiện các quyền dân chủ.',
      },
      {
        id: 'sq12_q2',
        text: 'Theo giáo trình, để quyền lực thực sự thuộc về nhân dân cần có cơ chế pháp luật bảo đảm những quyền gì?',
        hint: 'Quyền t_  d_ c_  _h_n, quyền l__  c__ nhà nước và quyền tham gia vào các q____  s___ của nhà nước.',
        answer: 'Quyền tự do cá nhân, quyền làm chủ nhà nước và quyền tham gia vào các quyết sách của nhà nước.',
        acceptedAnswers: ['Quyền tự do cá nhân, quyền làm chủ nhà nước và quyền tham gia vào các quyết sách của nhà nước.'],
        explanation: 'Quyền tự do cá nhân, quyền làm chủ nhà nước và quyền tham gia vào các quyết sách của nhà nước.',
      },
      {
        id: 'sq12_q3',
        text: 'Đúng hay sai: Chỉ cần tuyên bố quyền dân chủ là đủ, không cần cơ chế bảo đảm thực hiện.',
        hint: 'Sai. Cần các điều kiện và cơ chế p___  l___ để quyền dân chủ được thực hiện thực chất.',
        answer: 'Sai. Cần các điều kiện và cơ chế pháp luật để quyền dân chủ được thực hiện thực chất.',
        acceptedAnswers: ['Sai. Cần các điều kiện và cơ chế pháp luật để quyền dân chủ được thực hiện thực chất.'],
        explanation: 'Sai. Cần các điều kiện và cơ chế pháp luật để quyền dân chủ được thực hiện thực chất.',
      },
      {
        id: 'sq12_q4',
        text: 'Vì sao pháp luật không đối lập với dân chủ trong nội dung bài học?',
        hint: 'Vì dân chủ và pháp luật nằm trong sự t____  n___  b___  c____;\npháp luật thể chế hóa và bảo đảm dân chủ.',
        answer: 'Vì dân chủ và pháp luật nằm trong sự thống nhất biện chứng; pháp luật thể chế hóa và bảo đảm dân chủ.',
        acceptedAnswers: ['Vì dân chủ và pháp luật nằm trong sự thống nhất biện chứng; pháp luật thể chế hóa và bảo đảm dân chủ.'],
        explanation: 'Vì dân chủ và pháp luật nằm trong sự thống nhất biện chứng; pháp luật thể chế hóa và bảo đảm dân chủ.',
      },
    ],
  },
  {
    id: 13,
    name: 'QUẢN LÝ NHÀ NƯỚC',
    category: 'politics',
    subtitle: 'Nhân dân tham gia xây dựng bộ máy nhà nước',
    questions: [
      {
        id: 'sq13_q1',
        text: 'Nhân dân tham gia quản lý nhà nước thể hiện bản chất nào của nền dân chủ XHCN?',
        hint: 'Bản chất c____  t__.',
        answer: 'Bản chất chính trị.',
        acceptedAnswers: ['Bản chất chính trị.'],
        explanation: 'Bản chất chính trị.',
      },
      {
        id: 'sq13_q2',
        text: 'Theo giáo trình, ngoài việc giới thiệu đại biểu, nhân dân có thể tham gia vào quá trình nào của nhà nước?',
        hint: 'Xây dựng c____  s___, pháp luật và tham gia xây dựng b_  m__ nhà nước.',
        answer: 'Xây dựng chính sách, pháp luật và tham gia xây dựng bộ máy nhà nước.',
        acceptedAnswers: ['Xây dựng chính sách, pháp luật và tham gia xây dựng bộ máy nhà nước.'],
        explanation: 'Xây dựng chính sách, pháp luật và tham gia xây dựng bộ máy nhà nước.',
      },
      {
        id: 'sq13_q3',
        text: 'Sự tham gia rộng rãi của nhân dân vào quản lý nhà nước nhằm bảo đảm nguyên tắc nào?',
        hint: 'Mọi quyền lực thuộc về n___  d__;\ndân là c__ và dân l__  c__.',
        answer: 'Mọi quyền lực thuộc về nhân dân; dân là chủ và dân làm chủ.',
        acceptedAnswers: ['Mọi quyền lực thuộc về nhân dân; dân là chủ và dân làm chủ.'],
        explanation: 'Mọi quyền lực thuộc về nhân dân; dân là chủ và dân làm chủ.',
      },
      {
        id: 'sq13_q4',
        text: 'Trong nền dân chủ XHCN, quyền làm chủ của nhân dân được thực hiện trên phạm vi nào?',
        hint: 'Trên các l_nh  _uc của đ_i  số__  x_  _oi,\ntrong đó có quản lý nhà nước và xã hội.',
        answer: 'Trên các lĩnh vực của đời sống xã hội, trong đó có quản lý nhà nước và xã hội.',
        acceptedAnswers: ['Trên các lĩnh vực của đời sống xã hội, trong đó có quản lý nhà nước và xã hội.'],
        explanation: 'Trên các lĩnh vực của đời sống xã hội, trong đó có quản lý nhà nước và xã hội.',
      },
    ],
  },
  {
    id: 14,
    name: 'PHÂN PHỐI VÀ PHÚC LỢI',
    category: 'economy',
    subtitle: 'Phân phối theo lao động và thỏa mãn nhu cầu',
    questions: [
      {
        id: 'sq14_q1',
        text: 'Theo giáo trình, phân phối lợi ích trong nền dân chủ XHCN chủ yếu dựa theo yếu tố nào?',
        hint: 'Kết quả l__  đ___.',
        answer: 'Kết quả lao động.',
        acceptedAnswers: ['Kết quả lao động.'],
        explanation: 'Kết quả lao động.',
      },
      {
        id: 'sq14_q2',
        text: 'Phân phối có liên quan trực tiếp đến quyền làm chủ trên phương diện nào?',
        hint: 'K___  t_.',
        answer: 'Kinh tế.',
        acceptedAnswers: ['Kinh tế.'],
        explanation: 'Kinh tế.',
      },
      {
        id: 'sq14_q3',
        text: 'Việc bảo đảm lợi ích kinh tế của người lao động có ý nghĩa gì?',
        hint: 'Là một đ___  l__  c_  b__ thúc đẩy phát triển kinh tế – xã hội.',
        answer: 'Là một động lực cơ bản thúc đẩy phát triển kinh tế – xã hội.',
        acceptedAnswers: ['Là một động lực cơ bản thúc đẩy phát triển kinh tế – xã hội.'],
        explanation: 'Là một động lực cơ bản thúc đẩy phát triển kinh tế – xã hội.',
      },
      {
        id: 'sq14_q4',
        text: 'Mục tiêu cuối cùng của cơ sở kinh tế XHCN được giáo trình nêu là đáp ứng ngày càng cao những nhu cầu nào?',
        hint: 'Nhu cầu v__  c___ và t___  t___ của toàn thể nhân dân lao động.',
        answer: 'Nhu cầu vật chất và tinh thần của toàn thể nhân dân lao động.',
        acceptedAnswers: ['Nhu cầu vật chất và tinh thần của toàn thể nhân dân lao động.'],
        explanation: 'Nhu cầu vật chất và tinh thần của toàn thể nhân dân lao động.',
      },
    ],
  },
  {
    id: 15,
    name: 'VĂN HÓA VÀ ĐỜI SỐNG TINH THẦN',
    category: 'culture_society',
    subtitle: 'Kế thừa văn hóa dân tộc và tiếp thu tiến bộ nhân loại',
    questions: [
      {
        id: 'sq15_q1',
        text: 'Nền dân chủ XHCN kế thừa và phát huy những giá trị văn hóa nào?',
        hint: 'Tinh hoa văn hóa t____  t____ dân tộc.',
        answer: 'Tinh hoa văn hóa truyền thống dân tộc.',
        acceptedAnswers: ['Tinh hoa văn hóa truyền thống dân tộc.'],
        explanation: 'Tinh hoa văn hóa truyền thống dân tộc.',
      },
      {
        id: 'sq15_q2',
        text: 'Bên cạnh truyền thống dân tộc, nền dân chủ XHCN tiếp thu những gì từ nhân loại?',
        hint: 'Các giá trị t_  t____, văn hóa, v__  m___ và t___  b_ xã hội.',
        answer: 'Các giá trị tư tưởng, văn hóa, văn minh và tiến bộ xã hội.',
        acceptedAnswers: ['Các giá trị tư tưởng, văn hóa, văn minh và tiến bộ xã hội.'],
        explanation: 'Các giá trị tư tưởng, văn hóa, văn minh và tiến bộ xã hội.',
      },
      {
        id: 'sq15_q3',
        text: 'Nhân dân thực hiện quyền làm chủ trong đời sống văn hóa – tinh thần như thế nào?',
        hint: 'L__  c__, h____  t__ và tham gia s___  t__ các giá trị văn hóa, tinh thần.',
        answer: 'Làm chủ, hưởng thụ và tham gia sáng tạo các giá trị văn hóa, tinh thần.',
        acceptedAnswers: ['Làm chủ, hưởng thụ và tham gia sáng tạo các giá trị văn hóa, tinh thần.'],
        explanation: 'Làm chủ, hưởng thụ và tham gia sáng tạo các giá trị văn hóa, tinh thần.',
      },
      {
        id: 'sq15_q4',
        text: 'Bản chất tư tưởng – văn hóa của nền dân chủ XHCN lấy hệ tư tưởng nào làm chủ đạo?',
        hint: 'Chủ nghĩa M__ – L____.',
        answer: 'Chủ nghĩa Mác – Lênin.',
        acceptedAnswers: ['Chủ nghĩa Mác – Lênin.'],
        explanation: 'Chủ nghĩa Mác – Lênin.',
      },
    ],
  },
  {
    id: 16,
    name: 'KIẾN THỨC: NỀN DÂN CHỦ XHCN',
    category: 'knowledge',
    subtitle: 'Bản chất và vị trí lịch sử của dân chủ XHCN',
    questions: [
      {
        id: 'sq16_q1',
        text: 'Hoàn thành ý: Trong nền dân chủ XHCN, mọi quyền lực thuộc về ______.',
        hint: 'N___  d__.',
        answer: 'Nhân dân.',
        acceptedAnswers: ['Nhân dân.'],
        explanation: 'Nhân dân.',
      },
      {
        id: 'sq16_q2',
        text: 'Hai vế thể hiện địa vị và hoạt động của nhân dân trong nền dân chủ XHCN là gì?',
        hint: 'Dân là c__ và dân l__  c__.',
        answer: 'Dân là chủ và dân làm chủ.',
        acceptedAnswers: ['Dân là chủ và dân làm chủ.'],
        explanation: 'Dân là chủ và dân làm chủ.',
      },
      {
        id: 'sq16_q3',
        text: 'Nền dân chủ XHCN được giáo trình đánh giá như thế nào so với nền dân chủ tư sản?',
        hint: 'Là nền dân chủ cao hơn về c___.',
        answer: 'Là nền dân chủ cao hơn về chất.',
        acceptedAnswers: ['Là nền dân chủ cao hơn về chất.'],
        explanation: 'Là nền dân chủ cao hơn về chất.',
      },
      {
        id: 'sq16_q4',
        text: 'Nền dân chủ XHCN được thực hiện bằng nhà nước nào và đặt dưới sự lãnh đạo của lực lượng nào?',
        hint: 'Nhà nước p___  q____ XHCN, đặt dưới sự lãnh đạo của Đ___  C___  s__.',
        answer: 'Nhà nước pháp quyền XHCN, đặt dưới sự lãnh đạo của Đảng Cộng sản.',
        acceptedAnswers: ['Nhà nước pháp quyền XHCN, đặt dưới sự lãnh đạo của Đảng Cộng sản.'],
        explanation: 'Nhà nước pháp quyền XHCN, đặt dưới sự lãnh đạo của Đảng Cộng sản.',
      },
    ],
  },
  {
    id: 17,
    name: 'Y TẾ VÀ AN SINH XÃ HỘI',
    category: 'culture_society',
    subtitle: 'Bảo đảm an sinh và điều kiện phát triển con người',
    questions: [
      {
        id: 'sq17_q1',
        text: 'Việc bảo đảm điều kiện sống để con người phát triển gắn với phương diện nào của bản chất dân chủ XHCN?',
        hint: 'T_  t____ – văn hóa – x_  h__.',
        answer: 'Tư tưởng – văn hóa – xã hội.',
        acceptedAnswers: ['Tư tưởng – văn hóa – xã hội.'],
        explanation: 'Tư tưởng – văn hóa – xã hội.',
      },
      {
        id: 'sq17_q2',
        text: 'Bản chất kinh tế của nền dân chủ XHCN hướng tới thỏa mãn ngày càng cao những nhu cầu nào của nhân dân lao động?',
        hint: 'Nhu cầu v__  c___ và t___  t___.',
        answer: 'Nhu cầu vật chất và tinh thần.',
        acceptedAnswers: ['Nhu cầu vật chất và tinh thần.'],
        explanation: 'Nhu cầu vật chất và tinh thần.',
      },
      {
        id: 'sq17_q3',
        text: 'Khi xây dựng chính sách xã hội, ba nhóm lợi ích nào cần được kết hợp hài hòa?',
        hint: 'Lợi ích c_  _h_n, t__  t__ và t___  x_  h__.',
        answer: 'Lợi ích cá nhân, tập thể và toàn xã hội.',
        acceptedAnswers: ['Lợi ích cá nhân, tập thể và toàn xã hội.'],
        explanation: 'Lợi ích cá nhân, tập thể và toàn xã hội.',
      },
      {
        id: 'sq17_q4',
        text: 'Theo bản chất tư tưởng – văn hóa – xã hội, việc nâng cao trình độ văn hóa nhằm tạo điều kiện cho mỗi người phát triển điều gì?',
        hint: 'Phát triển c_  _h_n.',
        answer: 'Phát triển cá nhân.',
        acceptedAnswers: ['Phát triển cá nhân.'],
        explanation: 'Phát triển cá nhân.',
      },
    ],
  },
  {
    id: 18,
    name: 'TÌNH HUỐNG 3',
    category: 'scenario',
    subtitle: 'Tình huống cơ chế thực hiện và lợi ích',
    questions: [
      {
        id: 'sq18_q1',
        text: 'Một địa phương tổ chức lấy ý kiến dân nhưng ý kiến hợp pháp của người dân không có cơ chế tiếp nhận, phản hồi. Theo bài học còn thiếu điều kiện gì?',
        hint: 'Cơ chế p___  l___ và cơ chế thực hiện để quyền l__  c__ được bảo đảm thực chất.',
        answer: 'Cơ chế pháp luật và cơ chế thực hiện để quyền làm chủ được bảo đảm thực chất.',
        acceptedAnswers: ['Cơ chế pháp luật và cơ chế thực hiện để quyền làm chủ được bảo đảm thực chất.'],
        explanation: 'Cơ chế pháp luật và cơ chế thực hiện để quyền làm chủ được bảo đảm thực chất.',
      },
      {
        id: 'sq18_q2',
        text: 'Một doanh nghiệp phân phối lợi ích chủ yếu dựa trên kết quả lao động. Điều này phù hợp với phương diện nào?',
        hint: 'Bản c___ k___ tế.',
        answer: 'Bản chất kinh tế.',
        acceptedAnswers: ['Bản chất kinh tế.'],
        explanation: 'Bản chất kinh tế.',
      },
      {
        id: 'sq18_q3',
        text: 'Một chương trình giáo dục giúp người dân nâng cao trình độ và khả năng tham gia công việc xã hội. Điều này hỗ trợ việc thực hiện dân chủ ra sao?',
        hint: 'Tạo điều kiện để nhân dân có năng lực thực hiện quyền l__  c__ và phát triển c_  _h_n.',
        answer: 'Tạo điều kiện để nhân dân có năng lực thực hiện quyền làm chủ và phát triển cá nhân.',
        acceptedAnswers: ['Tạo điều kiện để nhân dân có năng lực thực hiện quyền làm chủ và phát triển cá nhân.'],
        explanation: 'Tạo điều kiện để nhân dân có năng lực thực hiện quyền làm chủ và phát triển cá nhân.',
      },
      {
        id: 'sq18_q4',
        text: 'Một cộng đồng chỉ bảo vệ lợi ích chung bằng cách phủ nhận hoàn toàn lợi ích cá nhân. Có phù hợp không?',
        hint: 'Không; cần kết hợp hài hòa lợi ích c_  _h_n, t__  t__ và t___  x_  h__.',
        answer: 'Không; cần kết hợp hài hòa lợi ích cá nhân, tập thể và toàn xã hội.',
        acceptedAnswers: ['Không; cần kết hợp hài hòa lợi ích cá nhân, tập thể và toàn xã hội.'],
        explanation: 'Không; cần kết hợp hài hòa lợi ích cá nhân, tập thể và toàn xã hội.',
      },
    ],
  },
  {
    id: 19,
    name: 'MÔI TRƯỜNG VÀ CỘNG ĐỒNG',
    category: 'culture_society',
    subtitle: 'Tính tích cực xã hội và hài hòa lợi ích',
    questions: [
      {
        id: 'sq19_q1',
        text: 'Khi giải quyết một vấn đề môi trường ảnh hưởng cả cộng đồng, cần kết hợp hài hòa những lợi ích nào theo giáo trình?',
        hint: 'Lợi ích c_  _h_n, t__  t__ và t___  x_  h__.',
        answer: 'Lợi ích cá nhân, tập thể và toàn xã hội.',
        acceptedAnswers: ['Lợi ích cá nhân, tập thể và toàn xã hội.'],
        explanation: 'Lợi ích cá nhân, tập thể và toàn xã hội.',
      },
      {
        id: 'sq19_q2',
        text: 'Việc người dân chủ động tham gia giải quyết công việc chung của cộng đồng thể hiện điều gì?',
        hint: 'Tính t___  c__ xã hội và quyền l__  c__ của nhân dân.',
        answer: 'Tính tích cực xã hội và quyền làm chủ của nhân dân.',
        acceptedAnswers: ['Tính tích cực xã hội và quyền làm chủ của nhân dân.'],
        explanation: 'Tính tích cực xã hội và quyền làm chủ của nhân dân.',
      },
      {
        id: 'sq19_q3',
        text: 'Bản chất xã hội của nền dân chủ XHCN hướng tới phát huy tiềm năng nào của nhân dân?',
        hint: 'Tiềm năng s___  t__ và tính t___  c__ xã hội.',
        answer: 'Tiềm năng sáng tạo và tính tích cực xã hội.',
        acceptedAnswers: ['Tiềm năng sáng tạo và tính tích cực xã hội.'],
        explanation: 'Tiềm năng sáng tạo và tính tích cực xã hội.',
      },
      {
        id: 'sq19_q4',
        text: 'Một quyết định cộng đồng chỉ hợp lý khi bảo đảm lợi ích của một cá nhân hay cần xem xét rộng hơn?',
        hint: 'Cần hài hòa lợi ích c_  _h_n, t__  t__ và t___  x_  h__.',
        answer: 'Cần hài hòa lợi ích cá nhân, tập thể và toàn xã hội.',
        acceptedAnswers: ['Cần hài hòa lợi ích cá nhân, tập thể và toàn xã hội.'],
        explanation: 'Cần hài hòa lợi ích cá nhân, tập thể và toàn xã hội.',
      },
    ],
  },
  {
    id: 20,
    name: 'QUYỀN VÀ NGHĨA VỤ CÔNG DÂN',
    category: 'politics',
    subtitle: 'Quyền con người, quyền công dân và nghĩa vụ',
    questions: [
      {
        id: 'sq20_q1',
        text: 'Dân chủ trong kinh tế và chính trị trực tiếp thể hiện những nhóm quyền nào của người dân?',
        hint: 'Quyền c__  n____ và quyền c___  d__.',
        answer: 'Quyền con người và quyền công dân.',
        acceptedAnswers: ['Quyền con người và quyền công dân.'],
        explanation: 'Quyền con người và quyền công dân.',
      },
      {
        id: 'sq20_q2',
        text: 'Quyền làm chủ của công dân có tách rời kỷ luật và kỷ cương không?',
        hint: 'Không.',
        answer: 'Không.',
        acceptedAnswers: ['Không.'],
        explanation: 'Không.',
      },
      {
        id: 'sq20_q3',
        text: '“Dân là chủ” nhấn mạnh điều gì về vị trí của nhân dân?',
        hint: 'Nhân dân là c__  t__, có địa vị l__  c__ xã hội.',
        answer: 'Nhân dân là chủ thể, có địa vị làm chủ xã hội.',
        acceptedAnswers: ['Nhân dân là chủ thể, có địa vị làm chủ xã hội.'],
        explanation: 'Nhân dân là chủ thể, có địa vị làm chủ xã hội.',
      },
      {
        id: 'sq20_q4',
        text: '“Dân làm chủ” nhấn mạnh điều gì?',
        hint: 'Nhân dân thực tế thực hiện và sử dụng quyền l__  c__ của mình.',
        answer: 'Nhân dân thực tế thực hiện và sử dụng quyền làm chủ của mình.',
        acceptedAnswers: ['Nhân dân thực tế thực hiện và sử dụng quyền làm chủ của mình.'],
        explanation: 'Nhân dân thực tế thực hiện và sử dụng quyền làm chủ của mình.',
      },
    ],
  },
  {
    id: 21,
    name: 'XÂY DỰNG CHÍNH SÁCH VÀ PHÁP LUẬT',
    category: 'law',
    subtitle: 'Kênh thể chế hóa quyền làm chủ của nhân dân',
    questions: [
      {
        id: 'sq21_q1',
        text: 'Việc nhân dân góp ý dự thảo chính sách, pháp luật thể hiện quyền gì?',
        hint: 'Quyền tham gia q___  l_ nhà nước và thực hiện quyền l__  c__ c____  t__.',
        answer: 'Quyền tham gia quản lý nhà nước và thực hiện quyền làm chủ chính trị.',
        acceptedAnswers: ['Quyền tham gia quản lý nhà nước và thực hiện quyền làm chủ chính trị.'],
        explanation: 'Quyền tham gia quản lý nhà nước và thực hiện quyền làm chủ chính trị.',
      },
      {
        id: 'sq21_q2',
        text: 'Vì sao chính sách và pháp luật là một kênh quan trọng để thực hiện dân chủ?',
        hint: 'Vì dân chủ cần được t__  c__ hóa bằng pháp luật và pháp luật bảo đảm.',
        answer: 'Vì dân chủ cần được thể chế hóa bằng pháp luật và pháp luật bảo đảm.',
        acceptedAnswers: ['Vì dân chủ cần được thể chế hóa bằng pháp luật và pháp luật bảo đảm.'],
        explanation: 'Vì dân chủ cần được thể chế hóa bằng pháp luật và pháp luật bảo đảm.',
      },
      {
        id: 'sq21_q3',
        text: 'Theo giáo trình, nhân dân có thể tham gia vào việc xây dựng những gì ngoài chính sách và pháp luật?',
        hint: 'B_  m__ nhà nước và đội ngũ c__  b_/đ__  b___ của mình.',
        answer: 'Bộ máy nhà nước và đội ngũ cán bộ/đại biểu của mình.',
        acceptedAnswers: ['Bộ máy nhà nước và đội ngũ cán bộ/đại biểu của mình.'],
        explanation: 'Bộ máy nhà nước và đội ngũ cán bộ/đại biểu của mình.',
      },
      {
        id: 'sq21_q4',
        text: 'Một chính sách dân chủ muốn được thực hiện ổn định cần gắn với những yêu cầu nào?',
        hint: 'P___  l___, k_  l___ và k_  c____.',
        answer: 'Pháp luật, kỷ luật và kỷ cương.',
        acceptedAnswers: ['Pháp luật, kỷ luật và kỷ cương.'],
        explanation: 'Pháp luật, kỷ luật và kỷ cương.',
      },
    ],
  },
  {
    id: 22,
    name: 'DOANH NGHIỆP VÀ LỢI ÍCH NGƯỜI LAO ĐỘNG',
    category: 'economy',
    subtitle: 'Dân chủ trong kinh doanh và quản lý doanh nghiệp',
    questions: [
      {
        id: 'sq22_q1',
        text: 'Trong doanh nghiệp, quyền làm chủ kinh tế của người lao động có thể thể hiện qua những hoạt động nào?',
        hint: 'Tham gia s__  x___, k___  d____, q___  l_ và p___  p___.',
        answer: 'Tham gia sản xuất, kinh doanh, quản lý và phân phối.',
        acceptedAnswers: ['Tham gia sản xuất, kinh doanh, quản lý và phân phối.'],
        explanation: 'Tham gia sản xuất, kinh doanh, quản lý và phân phối.',
      },
      {
        id: 'sq22_q2',
        text: 'Lợi ích kinh tế của ai là một động lực cơ bản theo bản chất kinh tế của dân chủ XHCN?',
        hint: 'Người l__  đ___.',
        answer: 'Người lao động.',
        acceptedAnswers: ['Người lao động.'],
        explanation: 'Người lao động.',
      },
      {
        id: 'sq22_q3',
        text: 'Phân phối lợi ích chủ yếu theo kết quả gì?',
        hint: 'Kết quả l__  đ___.',
        answer: 'Kết quả lao động.',
        acceptedAnswers: ['Kết quả lao động.'],
        explanation: 'Kết quả lao động.',
      },
      {
        id: 'sq22_q4',
        text: 'Nếu người lao động hoàn toàn không được tham gia quản lý và lợi ích không gắn với lao động, phương diện nào của quyền làm chủ bị hạn chế?',
        hint: 'Quyền l__  c__ về k___  t_.',
        answer: 'Quyền làm chủ về kinh tế.',
        acceptedAnswers: ['Quyền làm chủ về kinh tế.'],
        explanation: 'Quyền làm chủ về kinh tế.',
      },
    ],
  },
  {
    id: 23,
    name: 'TÌNH HUỐNG 4',
    category: 'scenario',
    subtitle: 'Tình huống tổng hợp bản chất dân chủ',
    questions: [
      {
        id: 'sq23_q1',
        text: 'Người dân được bầu đại diện, góp ý chính sách và tham gia quản lý công việc địa phương. Ba hoạt động này cùng thể hiện rõ nhất bản chất nào?',
        hint: 'Bản chất c____  t__.',
        answer: 'Bản chất chính trị.',
        acceptedAnswers: ['Bản chất chính trị.'],
        explanation: 'Bản chất chính trị.',
      },
      {
        id: 'sq23_q2',
        text: 'Người lao động được tham gia quản lý sản xuất, lợi ích gắn với kết quả lao động. Đây là biểu hiện tổng hợp của bản chất nào?',
        hint: 'Bản c___ k___ tế.',
        answer: 'Bản chất kinh tế.',
        acceptedAnswers: ['Bản chất kinh tế.'],
        explanation: 'Bản chất kinh tế.',
      },
      {
        id: 'sq23_q3',
        text: 'Một xã hội vừa phát huy văn hóa dân tộc, vừa tiếp thu giá trị tiến bộ của nhân loại và tạo điều kiện phát triển cá nhân. Đây là phương diện nào?',
        hint: 'Bản c___ tư __ở__ – văn hóa – xã hội.',
        answer: 'Bản chất tư tưởng – văn hóa – xã hội.',
        acceptedAnswers: ['Bản chất tư tưởng – văn hóa – xã hội.'],
        explanation: 'Bản chất tư tưởng – văn hóa – xã hội.',
      },
      {
        id: 'sq23_q4',
        text: 'Một người có quyền góp ý chính sách nhưng phải thực hiện quyền đó trong khuôn khổ pháp luật. Tình huống thể hiện mối quan hệ nào?',
        hint: 'Sự t____  n___  b___  c____ giữa dân chủ và pháp luật.',
        answer: 'Sự thống nhất biện chứng giữa dân chủ và pháp luật.',
        acceptedAnswers: ['Sự thống nhất biện chứng giữa dân chủ và pháp luật.'],
        explanation: 'Sự thống nhất biện chứng giữa dân chủ và pháp luật.',
      },
    ],
  },
  {
    id: 24,
    name: 'PHÁT TRIỂN CON NGƯỜI',
    category: 'culture_society',
    subtitle: 'Mục tiêu giải phóng con người và phát huy tiềm năng',
    questions: [
      {
        id: 'sq24_q1',
        text: 'Theo giáo trình, nâng cao trình độ văn hóa giúp nhân dân làm chủ những giá trị nào và tạo điều kiện cho điều gì?',
        hint: 'L__  c__ các giá trị văn hóa tinh thần và tạo điều kiện cho mỗi người phát triển c_  _h_n.',
        answer: 'Làm chủ các giá trị văn hóa tinh thần và tạo điều kiện cho mỗi người phát triển cá nhân.',
        acceptedAnswers: ['Làm chủ các giá trị văn hóa tinh thần và tạo điều kiện cho mỗi người phát triển cá nhân.'],
        explanation: 'Làm chủ các giá trị văn hóa tinh thần và tạo điều kiện cho mỗi người phát triển cá nhân.',
      },
      {
        id: 'sq24_q2',
        text: 'Việc phát huy tiềm năng sáng tạo của con người thuộc phương diện bản chất nào?',
        hint: 'T_  t____ – văn hóa – x_  h__.',
        answer: 'Tư tưởng – văn hóa – xã hội.',
        acceptedAnswers: ['Tư tưởng – văn hóa – xã hội.'],
        explanation: 'Tư tưởng – văn hóa – xã hội.',
      },
      {
        id: 'sq24_q3',
        text: 'Theo giáo trình, nhân dân phải được làm chủ không chỉ nhà nước và xã hội mà còn làm chủ điều gì ở chính mình?',
        hint: 'Chính b__  t___ mình và năng lực s___  t__ của mình.',
        answer: 'Chính bản thân mình và năng lực sáng tạo của mình.',
        acceptedAnswers: ['Chính bản thân mình và năng lực sáng tạo của mình.'],
        explanation: 'Chính bản thân mình và năng lực sáng tạo của mình.',
      },
      {
        id: 'sq24_q4',
        text: 'Theo nguyên tắc phát triển nền dân chủ XHCN, việc mở rộng dân chủ gắn với nâng cao mức độ giải phóng của lực lượng nào?',
        hint: 'Những người l__  đ___.',
        answer: 'Những người lao động.',
        acceptedAnswers: ['Những người lao động.'],
        explanation: 'Những người lao động.',
      },
    ],
  },
];
