import { BoardSquare, CategoryType } from '../types/game';

export const CATEGORY_CONFIG: Record<
  CategoryType,
  {
    label: string;
    description: string;
    bgClass: string;
    badgeClass: string;
    textColor: string;
    borderClass: string;
  }
> = {
  start: {
    label: 'Bắt đầu',
    description: 'Ô xuất phát của hành trình dân chủ',
    bgClass: 'bg-amber-50',
    badgeClass: 'bg-amber-500 text-white font-bold',
    textColor: 'text-amber-900',
    borderClass: 'border-amber-300',
  },
  politics: {
    label: 'Chính trị',
    description: 'Bản chất chính trị: quyền lực thuộc về nhân dân, tham gia quản lý nhà nước',
    bgClass: 'bg-rose-50',
    badgeClass: 'bg-rose-600 text-white',
    textColor: 'text-rose-950',
    borderClass: 'border-rose-300',
  },
  economy: {
    label: 'Kinh tế',
    description: 'Bản chất kinh tế: sở hữu TLSX chủ yếu, phân phối theo kết quả lao động',
    bgClass: 'bg-amber-50',
    badgeClass: 'bg-amber-600 text-white',
    textColor: 'text-amber-950',
    borderClass: 'border-amber-300',
  },
  culture_society: {
    label: 'Văn hóa – Xã hội',
    description: 'Bản chất tư tưởng - VH - XH: phát huy văn hóa dân tộc, nâng cao dân trí',
    bgClass: 'bg-sky-50',
    badgeClass: 'bg-sky-600 text-white',
    textColor: 'text-sky-950',
    borderClass: 'border-sky-300',
  },
  law: {
    label: 'Pháp luật',
    description: 'Thể chế hóa quyền dân chủ, kỷ luật, kỷ cương và pháp quyền XHCN',
    bgClass: 'bg-emerald-50',
    badgeClass: 'bg-emerald-600 text-white',
    textColor: 'text-emerald-950',
    borderClass: 'border-emerald-300',
  },
  knowledge: {
    label: 'Kiến thức cốt lõi',
    description: 'Khái niệm, nguồn gốc và quá trình phát triển của nền dân chủ',
    bgClass: 'bg-orange-50',
    badgeClass: 'bg-orange-500 text-white',
    textColor: 'text-orange-950',
    borderClass: 'border-orange-300',
  },
  scenario: {
    label: 'Tình huống thực tế',
    description: 'Vận dụng kiến thức giải quyết tình huống thực tiễn sinh động',
    bgClass: 'bg-purple-50',
    badgeClass: 'bg-purple-600 text-white',
    textColor: 'text-purple-950',
    borderClass: 'border-purple-300',
  },
};

export const BOARD_SQUARES: BoardSquare[] = [
  {
    id: 1,
    name: 'BẮT ĐẦU – HÀNH TRÌNH DÂN CHỦ',
    category: 'start',
    subtitle: 'Xuất phát điểm của hành trình làm chủ',
    questions: [
      {
        id: 'q000_1',
        text: 'Theo tư tưởng Hồ Chí Minh, hai vế ngắn gọn diễn đạt dân chủ là gì?',
        answerTemplate: '____ là chủ và ____ làm chủ',
        keyword: 'Dân; dân',
        hint: 'D__ là chủ và d__ làm chủ',
        answer: 'Dân là chủ và dân làm chủ',
        acceptedAnswers: ['dân là chủ và dân làm chủ', 'dân là chủ dân làm chủ', 'dân'],
      },
      {
        id: 'q000_2',
        text: 'Bản chất cao nhất của nền dân chủ XHCN là mọi quyền lực thuộc về ai?',
        answerTemplate: 'Mọi quyền lực thuộc về ____',
        keyword: 'nhân dân',
        hint: 'Mọi quyền lực thuộc về nh__ d__',
        answer: 'Nhân dân',
        acceptedAnswers: ['nhân dân', 'toàn thể nhân dân'],
      },
      {
        id: 'q000_3',
        text: 'Nền dân chủ XHCN đặt dưới sự lãnh đạo của lực lượng nào?',
        answerTemplate: 'Sự lãnh đạo của ____',
        keyword: 'Đảng Cộng sản',
        hint: 'Sự lãnh đạo của Đ___ C___ s__',
        answer: 'Đảng Cộng sản',
        acceptedAnswers: ['đảng cộng sản', 'đảng cộng sản việt nam'],
      },
      {
        id: 'q000_4',
        text: 'Mục tiêu cốt lõi của việc xây dựng nền dân chủ XHCN là gì?',
        answerTemplate: 'Dân giàu, nước mạnh, ____, ____, văn minh',
        keyword: 'dân chủ; công bằng',
        hint: 'Dân giàu, nước mạnh, d__ ch_, c___ b___, văn minh',
        answer: 'Dân chủ, công bằng',
        acceptedAnswers: ['dân chủ công bằng', 'dân chủ và công bằng', 'công bằng dân chủ'],
      },
    ],
  },
  {
    id: 2,
    name: 'KIẾN THỨC: KHÁI NIỆM DÂN CHỦ',
    category: 'knowledge',
    subtitle: 'Nguồn gốc và bản chất khái niệm dân chủ',
    questions: [
      {
        id: 'q001',
        text: 'Theo tư tưởng Hồ Chí Minh, hai vế ngắn gọn diễn đạt dân chủ là gì?',
        answerTemplate: '____ là chủ và ____ làm chủ',
        keyword: 'Dân; dân',
        hint: 'D__ là chủ và d__ làm chủ',
        answer: 'Dân là chủ và dân làm chủ',
        acceptedAnswers: ['dân là chủ và dân làm chủ', 'dân'],
      },
      {
        id: 'q002',
        text: 'Dân chủ được tiếp cận dưới ba tư cách cơ bản nào?',
        answerTemplate: 'Một giá trị ____; một phạm trù ____; một phạm trù ____',
        keyword: 'xã hội; chính trị; lịch sử',
        hint: 'Một giá trị x_ h__; một phạm trù chính trị; một phạm trù l___ s_',
        answer: 'Xã hội, chính trị, lịch sử',
        acceptedAnswers: [
          'giá trị xã hội, phạm trù chính trị, phạm trù lịch sử',
          'xã hội, chính trị, lịch sử',
          'xã hội chính trị lịch sử',
        ],
      },
      {
        id: 'q003',
        text: 'Dân chủ với tư cách một giá trị xã hội phản ánh điều gì?',
        answerTemplate: 'Những quyền cơ bản của ____',
        keyword: 'con người',
        hint: 'Những quyền cơ bản của c__ ng___',
        answer: 'Con người',
        acceptedAnswers: ['quyền cơ bản của con người', 'con người'],
      },
      {
        id: 'q004',
        text: 'Dân chủ bao quát những lĩnh vực chủ yếu nào?',
        answerTemplate: '____, ____, ____ và văn hóa – tinh thần – tư tưởng',
        keyword: 'kinh tế; chính trị; xã hội',
        hint: 'k___ t_; c____ t__; x_ h__ và văn hóa – tinh thần – tư tưởng',
        answer: 'Kinh tế, chính trị, xã hội',
        acceptedAnswers: [
          'kinh tế chính trị xã hội văn hóa tinh thần tư tưởng',
          'kinh tế chính trị xã hội',
          'kinh tế, chính trị, xã hội',
        ],
      },
    ],
  },
  {
    id: 3,
    name: 'PHÁT TRIỂN KINH TẾ BỀN VỮNG',
    category: 'economy',
    subtitle: 'Cơ sở kinh tế của nền dân chủ',
    questions: [
      {
        id: 'q005',
        text: 'Trong các lĩnh vực dân chủ, lĩnh vực nào được coi là cơ sở?',
        answerTemplate: 'Lĩnh vực ____',
        keyword: 'kinh tế',
        hint: 'Lĩnh vực k___ t_',
        answer: 'Kinh tế',
        acceptedAnswers: ['kinh tế', 'lĩnh vực kinh tế'],
      },
      {
        id: 'q006',
        text: 'Bản chất kinh tế của dân chủ XHCN hướng tới thỏa mãn nhu cầu của lực lượng nào?',
        answerTemplate: 'Toàn thể ____',
        keyword: 'nhân dân lao động',
        hint: 'Toàn thể nh__ d__ l__ đ___',
        answer: 'Nhân dân lao động',
        acceptedAnswers: ['nhân dân lao động', 'toàn thể nhân dân lao động'],
      },
      {
        id: 'q007',
        text: 'Quyền làm chủ về kinh tế trước hết gắn với loại tư liệu nào?',
        answerTemplate: 'Tư liệu sản xuất ____',
        keyword: 'chủ yếu',
        hint: 'Tư liệu sản xuất c__ y__',
        answer: 'Chủ yếu',
        acceptedAnswers: ['chủ yếu', 'tư liệu sản xuất chủ yếu'],
      },
      {
        id: 'q008',
        text: 'Lợi ích kinh tế của người lao động được coi là loại động lực nào?',
        answerTemplate: 'Một ____ thúc đẩy phát triển kinh tế – xã hội',
        keyword: 'động lực cơ bản',
        hint: 'Một đ___ l__ c_ b__ thúc đẩy phát triển kinh tế – xã hội',
        answer: 'Động lực cơ bản',
        acceptedAnswers: ['động lực cơ bản'],
      },
    ],
  },
  {
    id: 4,
    name: 'PHÁP LUẬT',
    category: 'law',
    subtitle: 'Kỷ luật, kỷ cương và thể chế hóa',
    questions: [
      {
        id: 'q009',
        text: 'Dân chủ và pháp luật trong nền dân chủ XHCN có mối quan hệ gì?',
        answerTemplate: 'Quan hệ ____',
        keyword: 'thống nhất biện chứng',
        hint: 'Quan hệ t____ n___ b___ c____',
        answer: 'Thống nhất biện chứng',
        acceptedAnswers: ['thống nhất biện chứng', 'quan hệ thống nhất biện chứng'],
      },
      {
        id: 'q010',
        text: 'Để bảo đảm trật tự xã hội, dân chủ phải đi đôi với hai yêu cầu nào?',
        answerTemplate: '____ và ____',
        keyword: 'kỷ luật; kỷ cương',
        hint: 'K_ l___ và k_ c____',
        answer: 'Kỷ luật và kỷ cương',
        acceptedAnswers: ['kỷ luật và kỷ cương', 'kỷ cương và kỷ luật', 'kỷ luật kỷ cương'],
      },
      {
        id: 'q011',
        text: 'Dân chủ phải được thể chế hóa và bảo đảm bằng công cụ nào?',
        answerTemplate: '____',
        keyword: 'pháp luật',
        hint: 'P___ l___',
        answer: 'Pháp luật',
        acceptedAnswers: ['pháp luật'],
      },
      {
        id: 'q012',
        text: 'Quyền dân chủ phải được thực hiện trong khuôn khổ nào?',
        answerTemplate: 'Khuôn khổ ____',
        keyword: 'pháp luật',
        hint: 'Khuôn khổ p___ l___',
        answer: 'Pháp luật',
        acceptedAnswers: ['pháp luật', 'khuôn khổ pháp luật'],
      },
    ],
  },
  {
    id: 5,
    name: 'TÌNH HUỐNG 1',
    category: 'scenario',
    subtitle: 'Thực tiễn giải quyết tình huống pháp luật và lợi ích',
    questions: [
      {
        id: 'q013',
        text: 'Có quyền làm chủ nhưng vẫn phải tuân thủ yếu tố nào cùng kỷ luật và kỷ cương?',
        answerTemplate: '____, kỷ luật và kỷ cương',
        keyword: 'pháp luật',
        hint: 'P___ l___, kỷ luật và kỷ cương',
        answer: 'Pháp luật',
        acceptedAnswers: ['pháp luật'],
      },
      {
        id: 'q014',
        text: 'Không cho dân tham gia ý kiến về vấn đề ảnh hưởng trực tiếp đến họ là chưa bảo đảm quyền nào?',
        answerTemplate: 'Quyền ____',
        keyword: 'làm chủ',
        hint: 'Quyền l__ c__',
        answer: 'Làm chủ',
        acceptedAnswers: ['làm chủ', 'quyền làm chủ'],
      },
      {
        id: 'q015',
        text: 'Chính sách chỉ chú ý một nhóm nhỏ cần kết hợp hài hòa ba nhóm lợi ích nào?',
        answerTemplate: 'Lợi ích ____, ____ và toàn xã hội',
        keyword: 'cá nhân; tập thể',
        hint: 'Lợi ích c_ n___, t__ t__ và toàn xã hội',
        answer: 'Cá nhân, tập thể',
        acceptedAnswers: ['cá nhân tập thể và toàn xã hội', 'cá nhân tập thể', 'cá nhân và tập thể'],
      },
      {
        id: 'q016',
        text: 'Phân phối lợi ích của người lao động chủ yếu phải dựa vào yếu tố nào?',
        answerTemplate: '____ lao động',
        keyword: 'kết quả',
        hint: 'K__ q__ lao động',
        answer: 'Kết quả',
        acceptedAnswers: ['kết quả', 'kết quả lao động'],
      },
    ],
  },
  {
    id: 6,
    name: 'THAM GIA QUẢN LÝ XÃ HỘI',
    category: 'politics',
    subtitle: 'Quyền lực nhân dân và quản trị xã hội',
    questions: [
      {
        id: 'q017',
        text: 'Nhân dân tham gia quản lý xã hội thể hiện trực tiếp bản chất nào?',
        answerTemplate: 'Bản chất ____',
        keyword: 'chính trị',
        hint: 'Bản chất c____ t__',
        answer: 'Chính trị',
        acceptedAnswers: ['chính trị', 'bản chất chính trị'],
      },
      {
        id: 'q018',
        text: 'Sự tham gia rộng rãi của nhân dân vào quản lý nhà nước được gọi là loại dân chủ nào?',
        answerTemplate: 'Dân chủ về ____',
        keyword: 'chính trị',
        hint: 'Dân chủ về c____ t__',
        answer: 'Chính trị',
        acceptedAnswers: ['chính trị', 'dân chủ về chính trị'],
      },
      {
        id: 'q019',
        text: 'Ngoài quản lý nhà nước, quyền làm chủ còn được thực hiện trong phạm vi nào?',
        answerTemplate: 'Trong ____ và các lĩnh vực của đời sống xã hội',
        keyword: 'toàn xã hội',
        hint: 'Trong t___ x_ h__ và các lĩnh vực của đời sống xã hội',
        answer: 'Toàn xã hội',
        acceptedAnswers: ['toàn xã hội'],
      },
      {
        id: 'q020',
        text: 'Thu hút nhân dân tham gia quản lý xã hội nhằm giúp họ thực hiện quyền gì?',
        answerTemplate: 'Quyền ____',
        keyword: 'làm chủ',
        hint: 'Quyền l__ c__',
        answer: 'Làm chủ',
        acceptedAnswers: ['làm chủ', 'quyền làm chủ'],
      },
    ],
  },
  {
    id: 7,
    name: 'BẦU CỬ',
    category: 'politics',
    subtitle: 'Dân chủ trực tiếp và đại diện',
    questions: [
      {
        id: 'q021',
        text: 'Nhân dân lựa chọn người đại diện thể hiện rõ nhất quyền làm chủ trên lĩnh vực nào?',
        answerTemplate: 'Lĩnh vực ____',
        keyword: 'chính trị',
        hint: 'Lĩnh vực c____ t__',
        answer: 'Chính trị',
        acceptedAnswers: ['chính trị', 'lĩnh vực chính trị'],
      },
      {
        id: 'q022',
        text: 'Bầu cử thể hiện rõ hơn vế nào: “dân là chủ” hay “dân làm chủ”?',
        answerTemplate: '____',
        keyword: 'dân làm chủ',
        hint: 'D__ l__ c__',
        answer: 'Dân làm chủ',
        acceptedAnswers: ['dân làm chủ'],
      },
      {
        id: 'q023',
        text: 'Nhân dân có quyền giới thiệu ai tham gia bộ máy chính quyền?',
        answerTemplate: 'Những ____ của mình',
        keyword: 'đại biểu',
        hint: 'Những đ__ b___ của mình',
        answer: 'Đại biểu',
        acceptedAnswers: ['đại biểu', 'những đại biểu của mình'],
      },
      {
        id: 'q024',
        text: 'Bầu cử và dân chủ trực tiếp bảo đảm quyền lực thuộc về ai?',
        answerTemplate: 'Quyền lực thuộc về ____',
        keyword: 'nhân dân',
        hint: 'Quyền lực thuộc về nh__ d__',
        answer: 'Nhân dân',
        acceptedAnswers: ['nhân dân'],
      },
    ],
  },
  {
    id: 8,
    name: 'KIẾN THỨC: SỰ RA ĐỜI VÀ PHÁT TRIỂN CỦA DÂN CHỦ',
    category: 'knowledge',
    subtitle: 'Lịch sử hình thành và tiến hóa của các nền dân chủ',
    questions: [
      {
        id: 'q025',
        text: 'Hình thức dân chủ sơ khai trong xã hội cộng sản nguyên thủy còn được gọi là gì?',
        answerTemplate: 'Dân chủ ____ / dân chủ ____',
        keyword: 'nguyên thủy; quân sự',
        hint: 'Dân chủ ng____ th__ / dân chủ q___ s_',
        answer: 'Nguyên thủy, quân sự',
        acceptedAnswers: [
          'nguyên thủy',
          'quân sự',
          'dân chủ nguyên thủy',
          'dân chủ quân sự',
          'nguyên thủy quân sự',
        ],
      },
      {
        id: 'q026',
        text: 'Xã hội chiếm hữu nô lệ xuất hiện nền dân chủ của giai cấp nào?',
        answerTemplate: 'Dân chủ ____',
        keyword: 'chủ nô',
        hint: 'Dân chủ c__ n_',
        answer: 'Chủ nô',
        acceptedAnswers: ['chủ nô', 'dân chủ chủ nô'],
      },
      {
        id: 'q027',
        text: 'Nền dân chủ XHCN chính thức được xác lập sau cuộc cách mạng nào?',
        answerTemplate: 'Cách mạng ____ Nga năm 1917',
        keyword: 'Tháng Mười',
        hint: 'Cách mạng Th___ M___ Nga năm 1917',
        answer: 'Tháng Mười',
        acceptedAnswers: ['tháng mười', 'cách mạng tháng mười nga', 'cách mạng tháng mười'],
      },
      {
        id: 'q028',
        text: 'Nền dân chủ XHCN phát triển từ trình độ nào đến trình độ nào?',
        answerTemplate: 'Từ ____ đến ____',
        keyword: 'thấp; cao',
        hint: 'Từ th__ đến c__',
        answer: 'Thấp đến cao',
        acceptedAnswers: ['thấp đến cao', 'từ thấp đến cao', 'thấp cao'],
      },
    ],
  },
  {
    id: 9,
    name: 'SẢN XUẤT VÀ LAO ĐỘNG',
    category: 'economy',
    subtitle: 'Lao động và quyền làm chủ tư liệu sản xuất',
    questions: [
      {
        id: 'q029',
        text: 'Người lao động thực hiện quyền làm chủ kinh tế qua ba hoạt động nào?',
        answerTemplate: '____, ____ và quản lý',
        keyword: 'sản xuất; kinh doanh',
        hint: 'S__ x___, k___ d____ và quản lý',
        answer: 'Sản xuất, kinh doanh',
        acceptedAnswers: ['sản xuất kinh doanh quản lý', 'sản xuất kinh doanh', 'sản xuất và kinh doanh'],
      },
      {
        id: 'q030',
        text: 'Nhân dân làm chủ loại tư liệu sản xuất nào?',
        answerTemplate: 'Tư liệu sản xuất ____',
        keyword: 'chủ yếu',
        hint: 'Tư liệu sản xuất c__ y__',
        answer: 'Chủ yếu',
        acceptedAnswers: ['chủ yếu', 'tư liệu sản xuất chủ yếu'],
      },
      {
        id: 'q031',
        text: 'Lợi ích kinh tế của lực lượng nào được coi là động lực cơ bản?',
        answerTemplate: 'Lợi ích kinh tế của ____',
        keyword: 'người lao động',
        hint: 'Lợi ích kinh tế của ng___ l__ đ___',
        answer: 'Người lao động',
        acceptedAnswers: ['người lao động'],
      },
      {
        id: 'q032',
        text: 'Bản chất kinh tế dựa trên lực lượng sản xuất ở trình độ nào?',
        answerTemplate: 'Trình độ ____ / hiện đại',
        keyword: 'cao',
        hint: 'Trình độ c__ / hiện đại',
        answer: 'Cao',
        acceptedAnswers: ['cao', 'hiện đại', 'trình độ cao'],
      },
    ],
  },
  {
    id: 10,
    name: 'TÌNH HUỐNG 2',
    category: 'scenario',
    subtitle: 'Tình huống dân chủ trong doanh nghiệp và văn hóa',
    questions: [
      {
        id: 'q033',
        text: 'Người lao động được góp ý tổ chức sản xuất và quản lý. Đây là bản chất nào?',
        answerTemplate: 'Bản chất ____',
        keyword: 'kinh tế',
        hint: 'Bản chất k___ t_',
        answer: 'Kinh tế',
        acceptedAnswers: ['kinh tế', 'bản chất kinh tế'],
      },
      {
        id: 'q034',
        text: 'Phát triển kinh tế phải hướng tới hai nhóm nhu cầu nào của nhân dân lao động?',
        answerTemplate: 'Nhu cầu ____ và ____',
        keyword: 'vật chất; tinh thần',
        hint: 'Nhu cầu v__ c___ và t___ th__',
        answer: 'Vật chất và tinh thần',
        acceptedAnswers: ['vật chất và tinh thần', 'tinh thần và vật chất', 'vật chất tinh thần'],
      },
      {
        id: 'q035',
        text: 'Người dân góp ý dự thảo chính sách thể hiện quyền làm chủ trên lĩnh vực nào?',
        answerTemplate: 'Làm chủ ____',
        keyword: 'chính trị',
        hint: 'Làm chủ c____ t__',
        answer: 'Chính trị',
        acceptedAnswers: ['chính trị', 'làm chủ chính trị'],
      },
      {
        id: 'q036',
        text: 'Hoạt động văn hóa không nên loại bỏ mà cần kế thừa giá trị nào?',
        answerTemplate: 'Tinh hoa văn hóa ____',
        keyword: 'dân tộc',
        hint: 'Tinh hoa văn hóa d__ t__',
        answer: 'Dân tộc',
        acceptedAnswers: ['dân tộc', 'tinh hoa văn hóa dân tộc'],
      },
    ],
  },
  {
    id: 11,
    name: 'GIÁO DỤC',
    category: 'culture_society',
    subtitle: 'Nâng cao dân trí và phát triển cá nhân',
    questions: [
      {
        id: 'q037',
        text: 'Nâng cao trình độ văn hóa tạo điều kiện cho mỗi người phát triển điều gì?',
        answerTemplate: 'Phát triển ____',
        keyword: 'cá nhân',
        hint: 'Phát triển c_ n___',
        answer: 'Cá nhân',
        acceptedAnswers: ['cá nhân', 'phát triển cá nhân'],
      },
      {
        id: 'q038',
        text: 'Cơ hội học tập và nâng cao trình độ gắn với phương diện bản chất nào?',
        answerTemplate: 'Bản chất ____ – ____ – ____',
        keyword: 'tư tưởng; văn hóa; xã hội',
        hint: 'Bản chất t_ t____ – v__ h__ – x_ h__',
        answer: 'Tư tưởng, văn hóa, xã hội',
        acceptedAnswers: ['tư tưởng văn hóa xã hội', 'tư tưởng, văn hóa, xã hội'],
      },
      {
        id: 'q039',
        text: 'Ngoài hưởng thụ, nhân dân còn làm gì với các giá trị văn hóa, tinh thần?',
        answerTemplate: 'Tham gia ____ các giá trị',
        keyword: 'sáng tạo',
        hint: 'Tham gia s___ t__ các giá trị',
        answer: 'Sáng tạo',
        acceptedAnswers: ['sáng tạo', 'tham gia sáng tạo'],
      },
      {
        id: 'q040',
        text: 'Để quyền lực thực sự thuộc về nhân dân cần nâng cao yếu tố nào?',
        answerTemplate: 'Trình độ ____',
        keyword: 'dân trí',
        hint: 'Trình độ d__ t__',
        answer: 'Dân trí',
        acceptedAnswers: ['dân trí', 'trình độ dân trí'],
      },
    ],
  },
  {
    id: 12,
    name: 'PHÁP LUẬT VÀ BẢO ĐẢM QUYỀN DÂN CHỦ',
    category: 'law',
    subtitle: 'Cơ chế pháp luật bảo vệ quyền con người',
    questions: [
      {
        id: 'q041',
        text: 'Pháp luật thực hiện hai vai trò nào đối với quyền dân chủ?',
        answerTemplate: '____ và ____ quyền dân chủ',
        keyword: 'thể chế hóa; bảo đảm',
        hint: 'Th_ ch_ h__ và b__ đ__ quyền dân chủ',
        answer: 'Thể chế hóa và bảo đảm',
        acceptedAnswers: ['thể chế hóa và bảo đảm', 'thể chế hóa bảo đảm', 'bảo đảm và thể chế hóa'],
      },
      {
        id: 'q042',
        text: 'Bên cạnh quyền làm chủ nhà nước, cơ chế pháp luật phải bảo đảm quyền cá nhân nào?',
        answerTemplate: 'Quyền ____ cá nhân',
        keyword: 'tự do',
        hint: 'Quyền t_ d_ cá nhân',
        answer: 'Tự do',
        acceptedAnswers: ['tự do', 'quyền tự do cá nhân', 'tự do cá nhân'],
      },
      {
        id: 'q043',
        text: 'Để quyền dân chủ được thực hiện thực chất cần có loại cơ chế nào?',
        answerTemplate: 'Cơ chế ____',
        keyword: 'pháp luật',
        hint: 'Cơ chế p___ l___',
        answer: 'Pháp luật',
        acceptedAnswers: ['pháp luật', 'cơ chế pháp luật'],
      },
      {
        id: 'q044',
        text: 'Dân chủ và pháp luật nằm trong mối quan hệ nào?',
        answerTemplate: 'Sự ____',
        keyword: 'thống nhất biện chứng',
        hint: 'Sự t____ n___ b___ c____',
        answer: 'Thống nhất biện chứng',
        acceptedAnswers: ['thống nhất biện chứng', 'sự thống nhất biện chứng'],
      },
    ],
  },
  {
    id: 13,
    name: 'QUẢN LÝ NHÀ NƯỚC',
    category: 'politics',
    subtitle: 'Xây dựng bộ máy nhà nước của nhân dân',
    questions: [
      {
        id: 'q045',
        text: 'Nhân dân tham gia quản lý nhà nước thể hiện bản chất nào?',
        answerTemplate: 'Bản chất ____',
        keyword: 'chính trị',
        hint: 'Bản chất c____ t__',
        answer: 'Chính trị',
        acceptedAnswers: ['chính trị', 'bản chất chính trị'],
      },
      {
        id: 'q046',
        text: 'Ngoài chính sách và pháp luật, nhân dân còn tham gia xây dựng bộ máy nào?',
        answerTemplate: 'Bộ máy ____',
        keyword: 'nhà nước',
        hint: 'Bộ máy nh_ n___',
        answer: 'Nhà nước',
        acceptedAnswers: ['nhà nước', 'bộ máy nhà nước'],
      },
      {
        id: 'q047',
        text: 'Sự tham gia rộng rãi của nhân dân bảo đảm quyền lực thuộc về ai?',
        answerTemplate: 'Mọi quyền lực thuộc về ____',
        keyword: 'nhân dân',
        hint: 'Mọi quyền lực thuộc về nh__ d__',
        answer: 'Nhân dân',
        acceptedAnswers: ['nhân dân'],
      },
      {
        id: 'q048',
        text: 'Quyền làm chủ của nhân dân được thực hiện trên phạm vi nào?',
        answerTemplate: 'Các lĩnh vực của ____',
        keyword: 'đời sống xã hội',
        hint: 'Các lĩnh vực của đ__ s___ x_ h__',
        answer: 'Đời sống xã hội',
        acceptedAnswers: ['đời sống xã hội'],
      },
    ],
  },
  {
    id: 14,
    name: 'PHÂN PHỐI VÀ PHÚC LỢI',
    category: 'economy',
    subtitle: 'Lợi ích kinh tế và phúc lợi xã hội',
    questions: [
      {
        id: 'q049',
        text: 'Phân phối lợi ích chủ yếu dựa theo yếu tố nào?',
        answerTemplate: '____ lao động',
        keyword: 'kết quả',
        hint: 'K__ q__ lao động',
        answer: 'Kết quả',
        acceptedAnswers: ['kết quả', 'kết quả lao động'],
      },
      {
        id: 'q050',
        text: 'Phân phối liên quan trực tiếp đến quyền làm chủ trên phương diện nào?',
        answerTemplate: 'Phương diện ____',
        keyword: 'kinh tế',
        hint: 'Phương diện k___ t_',
        answer: 'Kinh tế',
        acceptedAnswers: ['kinh tế', 'phương diện kinh tế'],
      },
      {
        id: 'q051',
        text: 'Lợi ích kinh tế của người lao động được coi là loại động lực nào?',
        answerTemplate: 'Một ____',
        keyword: 'động lực cơ bản',
        hint: 'Một đ___ l__ c_ b__',
        answer: 'Động lực cơ bản',
        acceptedAnswers: ['động lực cơ bản'],
      },
      {
        id: 'q052',
        text: 'Cơ sở kinh tế XHCN hướng tới đáp ứng hai nhóm nhu cầu nào?',
        answerTemplate: 'Nhu cầu ____ và ____',
        keyword: 'vật chất; tinh thần',
        hint: 'Nhu cầu v__ c___ và t___ th__',
        answer: 'Vật chất và tinh thần',
        acceptedAnswers: ['vật chất và tinh thần', 'tinh thần và vật chất', 'vật chất tinh thần'],
      },
    ],
  },
  {
    id: 15,
    name: 'VĂN HÓA VÀ ĐỜI SỐNG TINH THẦN',
    category: 'culture_society',
    subtitle: 'Kế thừa truyền thống và tiếp thu tinh hoa',
    questions: [
      {
        id: 'q053',
        text: 'Nền dân chủ XHCN kế thừa và phát huy loại tinh hoa văn hóa nào?',
        answerTemplate: 'Tinh hoa văn hóa ____',
        keyword: 'truyền thống dân tộc',
        hint: 'Tinh hoa văn hóa tr____ th___ d__ t__',
        answer: 'Truyền thống dân tộc',
        acceptedAnswers: ['truyền thống dân tộc', 'dân tộc'],
      },
      {
        id: 'q054',
        text: 'Bên cạnh truyền thống dân tộc, nền dân chủ XHCN tiếp thu loại giá trị nào của nhân loại?',
        answerTemplate: 'Các giá trị ____',
        keyword: 'tiến bộ',
        hint: 'Các giá trị t___ b_',
        answer: 'Tiến bộ',
        acceptedAnswers: ['tiến bộ', 'giá trị tiến bộ'],
      },
      {
        id: 'q055',
        text: 'Trong đời sống văn hóa – tinh thần, nhân dân vừa hưởng thụ vừa tham gia hoạt động nào?',
        answerTemplate: 'Tham gia ____ các giá trị văn hóa',
        keyword: 'sáng tạo',
        hint: 'Tham gia s___ t__ các giá trị văn hóa',
        answer: 'Sáng tạo',
        acceptedAnswers: ['sáng tạo', 'tham gia sáng tạo'],
      },
      {
        id: 'q056',
        text: 'Bản chất tư tưởng – văn hóa lấy hệ tư tưởng nào làm chủ đạo?',
        answerTemplate: 'Chủ nghĩa ____',
        keyword: 'Mác – Lênin',
        hint: 'Chủ nghĩa M__ – L____',
        answer: 'Mác – Lênin',
        acceptedAnswers: ['mác lênin', 'chủ nghĩa mác lênin', 'mác - lênin'],
      },
    ],
  },
  {
    id: 16,
    name: 'KIẾN THỨC: NỀN DÂN CHỦ XHCN',
    category: 'knowledge',
    subtitle: 'Bản chất ưu việt của nền dân chủ mới',
    questions: [
      {
        id: 'q057',
        text: 'Trong nền dân chủ XHCN, mọi quyền lực thuộc về ai?',
        answerTemplate: 'Mọi quyền lực thuộc về ____',
        keyword: 'nhân dân',
        hint: 'Mọi quyền lực thuộc về nh__ d__',
        answer: 'Nhân dân',
        acceptedAnswers: ['nhân dân'],
      },
      {
        id: 'q058',
        text: 'Hai vế thể hiện địa vị và hoạt động của nhân dân là gì?',
        answerTemplate: '____ là chủ và ____ làm chủ',
        keyword: 'dân; dân',
        hint: 'D__ là chủ và d__ làm chủ',
        answer: 'Dân là chủ và dân làm chủ',
        acceptedAnswers: ['dân là chủ và dân làm chủ', 'dân'],
      },
      {
        id: 'q059',
        text: 'So với dân chủ tư sản, dân chủ XHCN được đánh giá cao hơn về phương diện nào?',
        answerTemplate: 'Cao hơn về ____',
        keyword: 'chất',
        hint: 'Cao hơn về ch__',
        answer: 'Chất',
        acceptedAnswers: ['chất', 'bản chất'],
      },
      {
        id: 'q060',
        text: 'Nền dân chủ XHCN được đặt dưới sự lãnh đạo của lực lượng nào?',
        answerTemplate: 'Sự lãnh đạo của ____',
        keyword: 'Đảng Cộng sản',
        hint: 'Sự lãnh đạo của Đ___ C___ s__',
        answer: 'Đảng Cộng sản',
        acceptedAnswers: ['đảng cộng sản', 'đảng cộng sản việt nam'],
      },
    ],
  },
  {
    id: 17,
    name: 'Y TẾ VÀ AN SINH XÃ HỘI',
    category: 'culture_society',
    subtitle: 'Chăm sóc sức khỏe và phúc lợi cộng đồng',
    questions: [
      {
        id: 'q061',
        text: 'Bảo đảm điều kiện sống để con người phát triển gắn với phương diện bản chất nào?',
        answerTemplate: 'Bản chất ____ – ____ – ____',
        keyword: 'tư tưởng; văn hóa; xã hội',
        hint: 'Bản chất t_ t____ – v__ h__ – x_ h__',
        answer: 'Tư tưởng, văn hóa, xã hội',
        acceptedAnswers: ['tư tưởng văn hóa xã hội', 'tư tưởng, văn hóa, xã hội'],
      },
      {
        id: 'q062',
        text: 'Bản chất kinh tế hướng tới thỏa mãn hai nhóm nhu cầu nào?',
        answerTemplate: 'Nhu cầu ____ và ____',
        keyword: 'vật chất; tinh thần',
        hint: 'Nhu cầu v__ c___ và t___ th__',
        answer: 'Vật chất và tinh thần',
        acceptedAnswers: ['vật chất và tinh thần', 'tinh thần và vật chất', 'vật chất tinh thần'],
      },
      {
        id: 'q063',
        text: 'Chính sách xã hội cần kết hợp hài hòa lợi ích của ba phạm vi nào?',
        answerTemplate: '____, ____ và toàn xã hội',
        keyword: 'cá nhân; tập thể',
        hint: 'C_ n___, t__ t__ và toàn xã hội',
        answer: 'Cá nhân, tập thể',
        acceptedAnswers: ['cá nhân tập thể và toàn xã hội', 'cá nhân tập thể', 'cá nhân và tập thể'],
      },
      {
        id: 'q064',
        text: 'Nâng cao trình độ văn hóa nhằm tạo điều kiện phát triển điều gì?',
        answerTemplate: 'Phát triển ____',
        keyword: 'cá nhân',
        hint: 'Phát triển c_ n___',
        answer: 'Cá nhân',
        acceptedAnswers: ['cá nhân', 'phát triển cá nhân'],
      },
    ],
  },
  {
    id: 18,
    name: 'TÌNH HUỐNG 3',
    category: 'scenario',
    subtitle: 'Thực thi quy chế dân chủ ở cơ sở',
    questions: [
      {
        id: 'q065',
        text: 'Lấy ý kiến dân nhưng không có cách tiếp nhận, phản hồi thì còn thiếu loại cơ chế nào?',
        answerTemplate: 'Cơ chế ____',
        keyword: 'pháp luật và thực hiện',
        hint: 'Cơ chế p___ l___ và th__ h___',
        answer: 'Pháp luật và thực hiện',
        acceptedAnswers: [
          'pháp luật và thực hiện',
          'cơ chế pháp luật và cơ chế thực hiện',
          'pháp luật và cơ chế thực hiện',
        ],
      },
      {
        id: 'q066',
        text: 'Phân phối lợi ích chủ yếu theo kết quả lao động phù hợp với bản chất nào?',
        answerTemplate: 'Bản chất ____',
        keyword: 'kinh tế',
        hint: 'Bản chất k___ t_',
        answer: 'Kinh tế',
        acceptedAnswers: ['kinh tế', 'bản chất kinh tế'],
      },
      {
        id: 'q067',
        text: 'Giáo dục nâng cao khả năng tham gia công việc xã hội giúp tăng năng lực gì?',
        answerTemplate: 'Năng lực ____',
        keyword: 'làm chủ',
        hint: 'Năng lực l__ c__',
        answer: 'Làm chủ',
        acceptedAnswers: ['làm chủ', 'năng lực làm chủ'],
      },
      {
        id: 'q068',
        text: 'Không được phủ nhận lợi ích cá nhân; cần bảo đảm quan hệ nào giữa các lợi ích?',
        answerTemplate: '____ các lợi ích',
        keyword: 'hài hòa',
        hint: 'H__ h__ các lợi ích',
        answer: 'Hài hòa',
        acceptedAnswers: ['hài hòa', 'hài hòa lợi ích'],
      },
    ],
  },
  {
    id: 19,
    name: 'MÔI TRƯỜNG VÀ CỘNG ĐỒNG',
    category: 'culture_society',
    subtitle: 'Trách nhiệm cộng đồng và môi trường sống',
    questions: [
      {
        id: 'q069',
        text: 'Giải quyết vấn đề môi trường cộng đồng cần kết hợp ba nhóm lợi ích nào?',
        answerTemplate: 'Lợi ích ____, ____ và toàn xã hội',
        keyword: 'cá nhân; tập thể',
        hint: 'Lợi ích c_ n___, t__ t__ và toàn xã hội',
        answer: 'Cá nhân, tập thể',
        acceptedAnswers: ['cá nhân tập thể và toàn xã hội', 'cá nhân tập thể', 'cá nhân và tập thể'],
      },
      {
        id: 'q070',
        text: 'Chủ động tham gia công việc chung thể hiện tính chất xã hội nào?',
        answerTemplate: 'Tính ____ xã hội',
        keyword: 'tích cực',
        hint: 'Tính t___ c__ xã hội',
        answer: 'Tích cực',
        acceptedAnswers: ['tích cực', 'tính tích cực xã hội', 'tính tích cực'],
      },
      {
        id: 'q071',
        text: 'Bản chất xã hội hướng tới phát huy tiềm năng nào của nhân dân?',
        answerTemplate: 'Tiềm năng ____',
        keyword: 'sáng tạo',
        hint: 'Tiềm năng s___ t__',
        answer: 'Sáng tạo',
        acceptedAnswers: ['sáng tạo', 'tiềm năng sáng tạo'],
      },
      {
        id: 'q072',
        text: 'Quyết định cộng đồng cần bảo đảm quan hệ nào giữa các lợi ích?',
        answerTemplate: '____ lợi ích',
        keyword: 'hài hòa',
        hint: 'H__ h__ lợi ích',
        answer: 'Hài hòa',
        acceptedAnswers: ['hài hòa', 'hài hòa lợi ích'],
      },
    ],
  },
  {
    id: 20,
    name: 'QUYỀN VÀ NGHĨA VỤ CÔNG DÂN',
    category: 'politics',
    subtitle: 'Mối quan hệ giữa quyền và trách nhiệm công dân',
    questions: [
      {
        id: 'q073',
        text: 'Dân chủ trong kinh tế và chính trị trực tiếp thể hiện hai nhóm quyền nào?',
        answerTemplate: 'Quyền ____ và quyền ____',
        keyword: 'con người; công dân',
        hint: 'Quyền c__ ng___ và quyền c___ d__',
        answer: 'Quyền con người và quyền công dân',
        acceptedAnswers: [
          'quyền con người và quyền công dân',
          'con người và công dân',
          'công dân và con người',
          'con người công dân',
        ],
      },
      {
        id: 'q074',
        text: 'Quyền làm chủ phải gắn với hai yêu cầu bảo đảm trật tự nào?',
        answerTemplate: '____ và ____',
        keyword: 'kỷ luật; kỷ cương',
        hint: 'K_ l___ và k_ c____',
        answer: 'Kỷ luật và kỷ cương',
        acceptedAnswers: ['kỷ luật và kỷ cương', 'kỷ cương và kỷ luật', 'kỷ luật kỷ cương'],
      },
      {
        id: 'q075',
        text: '“Dân là chủ” nhấn mạnh nhân dân giữ vị trí gì?',
        answerTemplate: 'Nhân dân là ____',
        keyword: 'chủ thể',
        hint: 'Nhân dân là ch_ th_',
        answer: 'Chủ thể',
        acceptedAnswers: ['chủ thể', 'nhân dân là chủ thể'],
      },
      {
        id: 'q076',
        text: '“Dân làm chủ” nhấn mạnh nhân dân làm gì với quyền làm chủ?',
        answerTemplate: '____ quyền làm chủ',
        keyword: 'thực hiện',
        hint: 'Th__ h___ quyền làm chủ',
        answer: 'Thực hiện',
        acceptedAnswers: ['thực hiện', 'thực hiện quyền làm chủ'],
      },
    ],
  },
  {
    id: 21,
    name: 'XÂY DỰNG CHÍNH SÁCH VÀ PHÁP LUẬT',
    category: 'law',
    subtitle: 'Nhân dân tham gia hoàn thiện thể chế',
    questions: [
      {
        id: 'q077',
        text: 'Góp ý dự thảo chính sách, pháp luật thể hiện quyền tham gia hoạt động nào?',
        answerTemplate: 'Tham gia ____ nhà nước',
        keyword: 'quản lý',
        hint: 'Tham gia q___ l_ nhà nước',
        answer: 'Quản lý',
        acceptedAnswers: ['quản lý', 'quản lý nhà nước'],
      },
      {
        id: 'q078',
        text: 'Dân chủ được chuyển thành quy định pháp luật thông qua quá trình nào?',
        answerTemplate: '____ dân chủ bằng pháp luật',
        keyword: 'thể chế hóa',
        hint: 'Th_ ch_ h__ dân chủ bằng pháp luật',
        answer: 'Thể chế hóa',
        acceptedAnswers: ['thể chế hóa'],
      },
      {
        id: 'q079',
        text: 'Ngoài chính sách và pháp luật, nhân dân còn tham gia xây dựng bộ máy nào?',
        answerTemplate: 'Bộ máy ____',
        keyword: 'nhà nước',
        hint: 'Bộ máy nh_ n___',
        answer: 'Nhà nước',
        acceptedAnswers: ['nhà nước', 'bộ máy nhà nước'],
      },
      {
        id: 'q080',
        text: 'Chính sách dân chủ ổn định phải gắn với pháp luật và hai yêu cầu nào?',
        answerTemplate: 'Pháp luật, ____ và ____',
        keyword: 'kỷ luật; kỷ cương',
        hint: 'Pháp luật, k_ l___ và k_ c____',
        answer: 'Kỷ luật và kỷ cương',
        acceptedAnswers: ['kỷ luật và kỷ cương', 'kỷ cương và kỷ luật', 'kỷ luật kỷ cương'],
      },
    ],
  },
  {
    id: 22,
    name: 'DOANH NGHIỆP VÀ LỢI ÍCH NGƯỜI LAO ĐỘNG',
    category: 'economy',
    subtitle: 'Dân chủ cơ sở tại nơi làm việc',
    questions: [
      {
        id: 'q081',
        text: 'Quyền làm chủ kinh tế trong doanh nghiệp thể hiện qua bốn hoạt động nào?',
        answerTemplate: '____, ____, quản lý và phân phối',
        keyword: 'sản xuất; kinh doanh',
        hint: 'S__ x___, k___ d____, quản lý và phân phối',
        answer: 'Sản xuất, kinh doanh',
        acceptedAnswers: [
          'sản xuất kinh doanh quản lý phân phối',
          'sản xuất kinh doanh',
          'sản xuất và kinh doanh',
        ],
      },
      {
        id: 'q082',
        text: 'Lợi ích kinh tế của lực lượng nào là một động lực cơ bản?',
        answerTemplate: 'Lợi ích kinh tế của ____',
        keyword: 'người lao động',
        hint: 'Lợi ích kinh tế của ng___ l__ đ___',
        answer: 'Người lao động',
        acceptedAnswers: ['người lao động'],
      },
      {
        id: 'q083',
        text: 'Phân phối lợi ích chủ yếu dựa theo kết quả gì?',
        answerTemplate: 'Kết quả ____',
        keyword: 'lao động',
        hint: 'Kết quả l__ đ___',
        answer: 'Lao động',
        acceptedAnswers: ['lao động', 'kết quả lao động'],
      },
      {
        id: 'q084',
        text: 'Không được tham gia quản lý và lợi ích không gắn với lao động làm hạn chế quyền làm chủ nào?',
        answerTemplate: 'Quyền làm chủ về ____',
        keyword: 'kinh tế',
        hint: 'Quyền làm chủ về k___ t_',
        answer: 'Kinh tế',
        acceptedAnswers: ['kinh tế', 'quyền làm chủ về kinh tế'],
      },
    ],
  },
  {
    id: 23,
    name: 'TÌNH HUỐNG 4',
    category: 'scenario',
    subtitle: 'Tổng kết vận dụng các nguyên tắc dân chủ',
    questions: [
      {
        id: 'q085',
        text: 'Bầu đại diện, góp ý chính sách và quản lý địa phương cùng thể hiện rõ nhất bản chất nào?',
        answerTemplate: 'Bản chất ____',
        keyword: 'chính trị',
        hint: 'Bản chất c____ t__',
        answer: 'Chính trị',
        acceptedAnswers: ['chính trị', 'bản chất chính trị'],
      },
      {
        id: 'q086',
        text: 'Tham gia quản lý sản xuất và lợi ích gắn với kết quả lao động thể hiện bản chất nào?',
        answerTemplate: 'Bản chất ____',
        keyword: 'kinh tế',
        hint: 'Bản chất k___ t_',
        answer: 'Kinh tế',
        acceptedAnswers: ['kinh tế', 'bản chất kinh tế'],
      },
      {
        id: 'q087',
        text: 'Phát huy văn hóa dân tộc, tiếp thu giá trị tiến bộ và phát triển cá nhân thể hiện bản chất nào?',
        answerTemplate: 'Bản chất ____ – ____ – ____',
        keyword: 'tư tưởng; văn hóa; xã hội',
        hint: 'Bản chất t_ t____ – v__ h__ – x_ h__',
        answer: 'Tư tưởng, văn hóa, xã hội',
        acceptedAnswers: ['tư tưởng văn hóa xã hội', 'tư tưởng, văn hóa, xã hội'],
      },
      {
        id: 'q088',
        text: 'Có quyền góp ý nhưng phải trong khuôn khổ pháp luật thể hiện sự thống nhất giữa hai yếu tố nào?',
        answerTemplate: '____ và ____',
        keyword: 'dân chủ; pháp luật',
        hint: 'D__ ch_ và p___ l___',
        answer: 'Dân chủ và pháp luật',
        acceptedAnswers: ['dân chủ và pháp luật', 'pháp luật và dân chủ', 'dân chủ pháp luật'],
      },
    ],
  },
  {
    id: 24,
    name: 'PHÁT TRIỂN CON NGƯỜI',
    category: 'culture_society',
    subtitle: 'Giải phóng và phát triển toàn diện con người',
    questions: [
      {
        id: 'q089',
        text: 'Nâng cao trình độ văn hóa tạo điều kiện cho mỗi người phát triển điều gì?',
        answerTemplate: 'Phát triển ____',
        keyword: 'cá nhân',
        hint: 'Phát triển c_ n___',
        answer: 'Cá nhân',
        acceptedAnswers: ['cá nhân', 'phát triển cá nhân'],
      },
      {
        id: 'q090',
        text: 'Phát huy tiềm năng sáng tạo thuộc phương diện bản chất nào?',
        answerTemplate: 'Bản chất ____ – ____ – ____',
        keyword: 'tư tưởng; văn hóa; xã hội',
        hint: 'Bản chất t_ t____ – v__ h__ – x_ h__',
        answer: 'Tư tưởng, văn hóa, xã hội',
        acceptedAnswers: ['tư tưởng văn hóa xã hội', 'tư tưởng, văn hóa, xã hội'],
      },
      {
        id: 'q091',
        text: 'Ngoài nhà nước và xã hội, nhân dân còn phải làm chủ đối tượng nào ở chính mình?',
        answerTemplate: 'Làm chủ ____',
        keyword: 'bản thân mình',
        hint: 'Làm chủ b__ th__ m___',
        answer: 'Bản thân mình',
        acceptedAnswers: ['bản thân mình', 'chính bản thân mình', 'bản thân'],
      },
      {
        id: 'q092',
        text: 'Mở rộng dân chủ gắn với nâng cao mức độ giải phóng lực lượng nào?',
        answerTemplate: 'Giải phóng ____',
        keyword: 'người lao động',
        hint: 'Giải phóng ng___ l__ đ___',
        answer: 'Người lao động',
        acceptedAnswers: ['người lao động', 'giải phóng người lao động'],
      },
    ],
  },
];
